"""
diagram_renderers.py — Renderers for generating Mermaid architecture diagrams.

Produces Mermaid diagram syntax for various architectural views.
"""

from __future__ import annotations

import datetime
from typing import List

from aios.docgen.diagram_models import (
    ArchitecturalComponent,
    BootstrapStep,
    DIBinding,
    LifecyclePhase,
    PersistenceLayer,
    ServiceNode,
)

_TIMESTAMP_FMT = "%Y-%m-%dT%H:%M:%SZ"


def _banner() -> str:
    """Generate the auto-generated warning banner."""
    now = datetime.datetime.now(datetime.UTC).strftime(_TIMESTAMP_FMT)
    return f"""<!--
  ⚠  AUTO-GENERATED — DO NOT EDIT MANUALLY
  Generated by: aios.docgen diagram generator
  Generated on: {now}
  This file is recreated on every generation run.
  Edit the source code and re-run the generator to update this file.
-->

"""


def render_overall_architecture(components: List[ArchitecturalComponent]) -> str:
    """Render the overall AI OS architecture diagram."""
    lines = [_banner()]
    lines.append("# AI OS Architecture\n\n")
    lines.append(
        "> High-level system architecture showing major components and their relationships.\n\n"
    )

    lines.append("## Overall Architecture\n\n")
    lines.append("```mermaid\n")
    lines.append("graph TB\n")

    # Define nodes with styling
    for comp in components:
        style = ""
        if comp.type == "kernel":
            style = ":::kernelStyle"
        elif comp.type == "engine":
            style = ":::engineStyle"
        elif comp.type == "service":
            style = ":::serviceStyle"
        elif comp.type == "interface":
            style = ":::interfaceStyle"

        node_id = comp.name.replace(" ", "_")
        lines.append(f"    {node_id}[{comp.name}]{style}\n")

    # Add dependencies
    for comp in components:
        node_id = comp.name.replace(" ", "_")
        for dep in comp.dependencies:
            dep_id = dep.replace(" ", "_")
            lines.append(f"    {node_id} --> {dep_id}\n")

    # Add subcomponent relationships
    for comp in components:
        if comp.subcomponents:
            node_id = comp.name.replace(" ", "_")
            for sub in comp.subcomponents:
                sub_id = sub.replace(" ", "_")
                lines.append(f"    {node_id} -.-> {sub_id}\n")

    # Define styles
    lines.append("\n    classDef kernelStyle fill:#ff6b6b,stroke:#c92a2a,stroke-width:3px\n")
    lines.append("    classDef engineStyle fill:#4dabf7,stroke:#1971c2,stroke-width:2px\n")
    lines.append("    classDef serviceStyle fill:#51cf66,stroke:#2f9e44,stroke-width:2px\n")
    lines.append("    classDef interfaceStyle fill:#ffd43b,stroke:#f08c00,stroke-width:2px\n")
    lines.append("```\n\n")

    # Legend
    lines.append("## Component Types\n\n")
    lines.append("- **Kernel** (red): Core orchestration engine\n")
    lines.append("- **Engine** (blue): Processing and reasoning engines\n")
    lines.append("- **Service** (green): System services and coordinators\n")
    lines.append("- **Interface** (yellow): External interfaces and entry points\n\n")

    lines.append("**Solid arrows** (→) represent dependencies\n")
    lines.append("**Dotted arrows** (⇢) represent subcomponent relationships\n")

    return "".join(lines)


def render_service_dependency_graph(services: List[ServiceNode]) -> str:
    """Render the service dependency graph."""
    lines = [_banner()]
    lines.append("# Service Dependency Graph\n\n")
    lines.append(f"> Dependency relationships between {len(services)} services.\n\n")

    lines.append("## Service Dependencies\n\n")
    lines.append("```mermaid\n")
    lines.append("graph LR\n")

    # Only show services with dependencies to keep graph readable
    services_with_deps = [s for s in services if s.dependencies]

    for service in services_with_deps[:30]:  # Limit to first 30 to keep readable
        node_id = service.name.replace("Service", "").replace("Engine", "")
        style = ":::interfaceStyle" if service.is_interface else ":::implStyle"

        for dep in service.dependencies[:5]:  # Limit deps per service
            dep_id = dep.replace("Service", "").replace("Engine", "")
            lines.append(f"    {node_id}{style} --> {dep_id}\n")

    lines.append("\n    classDef interfaceStyle fill:#4dabf7,stroke:#1971c2,stroke-width:2px\n")
    lines.append("    classDef implStyle fill:#51cf66,stroke:#2f9e44,stroke-width:2px\n")
    lines.append("```\n\n")

    lines.append("## Legend\n\n")
    lines.append("- **Blue nodes**: Service interfaces\n")
    lines.append("- **Green nodes**: Service implementations\n")
    lines.append("- **Arrows**: Service depends on target\n\n")

    lines.append(
        f"Note: Showing {min(30, len(services_with_deps))} services with the most dependencies "
    )
    lines.append(f"out of {len(services)} total services.\n")

    return "".join(lines)


def render_di_graph(bindings: List[DIBinding]) -> str:
    """Render the dependency injection bindings graph."""
    lines = [_banner()]
    lines.append("# Dependency Injection Graph\n\n")
    lines.append(f"> DI bindings showing {len(bindings)} interface to implementation mappings.\n\n")

    lines.append("## DI Bindings\n\n")
    lines.append("```mermaid\n")
    lines.append("graph LR\n")

    # Group by module for better organization
    for binding in bindings[:40]:  # Limit to first 40 for readability
        iface_id = binding.interface.replace("Service", "").replace("Interface", "")
        concrete_id = binding.concrete.replace("Service", "").replace("Impl", "")

        lines.append(f"    {iface_id}[{iface_id}]:::interfaceStyle --> ")
        lines.append(f"{concrete_id}[{concrete_id}]:::implStyle\n")

    lines.append("\n    classDef interfaceStyle fill:#ffd43b,stroke:#f08c00,stroke-width:2px\n")
    lines.append("    classDef implStyle fill:#51cf66,stroke:#2f9e44,stroke-width:2px\n")
    lines.append("```\n\n")

    lines.append("## Legend\n\n")
    lines.append("- **Yellow nodes**: Interface types\n")
    lines.append("- **Green nodes**: Concrete implementations\n")
    lines.append("- **Arrows**: Interface is bound to implementation\n\n")

    lines.append(f"Note: Showing {min(40, len(bindings))} bindings out of {len(bindings)} total.\n")

    return "".join(lines)


def render_lifecycle_diagram(phases: List[LifecyclePhase]) -> str:
    """Render the runtime lifecycle diagram."""
    lines = [_banner()]
    lines.append("# Runtime Lifecycle\n\n")
    lines.append("> Service lifecycle phases from initialization through cleanup.\n\n")

    lines.append("## Lifecycle Flow\n\n")
    lines.append("```mermaid\n")
    lines.append("stateDiagram-v2\n")

    # Create state transitions
    lines.append("    [*] --> Initialization\n")

    prev_phase = None
    for phase in sorted(phases, key=lambda p: p.order):
        phase_id = phase.name.capitalize()
        if prev_phase:
            lines.append(f"    {prev_phase} --> {phase_id}\n")
        prev_phase = phase_id

    if prev_phase:
        lines.append(f"    {prev_phase} --> [*]\n\n")

    # Add details for each phase
    for phase in sorted(phases, key=lambda p: p.order):
        phase_id = phase.name.capitalize()
        lines.append(f"    state {phase_id} {{\n")
        for _i, service in enumerate(phase.services[:8]):  # Limit to 8 per phase
            service_short = service.replace("Service", "").replace("Impl", "")
            lines.append(f"        {service_short}\n")
        if len(phase.services) > 8:
            lines.append(f"        ... {len(phase.services) - 8} more\n")
        lines.append("    }\n")

    lines.append("```\n\n")

    lines.append("## Lifecycle Phases\n\n")
    for phase in sorted(phases, key=lambda p: p.order):
        lines.append(f"### {phase.name.capitalize()}\n\n")
        lines.append(f"Services in this phase: {len(phase.services)}\n\n")
        if phase.services[:5]:
            lines.append("Key services:\n")
            for service in phase.services[:5]:
                lines.append(f"- {service}\n")
            lines.append("\n")

    return "".join(lines)


def render_bootstrap_sequence(steps: List[BootstrapStep]) -> str:
    """Render the bootstrap sequence diagram."""
    lines = [_banner()]
    lines.append("# Bootstrap Sequence\n\n")
    lines.append("> System initialization sequence showing bootstrap steps.\n\n")

    lines.append("## Bootstrap Flow\n\n")
    lines.append("```mermaid\n")
    lines.append("sequenceDiagram\n")
    lines.append("    participant Main\n")
    lines.append("    participant Bootstrap\n")
    lines.append("    participant Kernel\n")
    lines.append("    participant Services\n\n")

    # Add bootstrap steps
    lines.append("    Main->>Bootstrap: start()\n")

    for step in sorted(steps, key=lambda s: s.order)[:15]:  # Limit to first 15 steps
        if "Registry" in step.name or "Container" in step.name:
            lines.append(f"    Bootstrap->>Bootstrap: {step.name}\n")
        elif "Kernel" in step.name:
            lines.append(f"    Bootstrap->>Kernel: {step.name}\n")
        else:
            lines.append(f"    Bootstrap->>Services: {step.name}\n")

    lines.append("    Bootstrap->>Kernel: initialize()\n")
    lines.append("    Kernel-->>Main: ready\n")
    lines.append("```\n\n")

    lines.append("## Bootstrap Steps\n\n")
    for i, step in enumerate(sorted(steps, key=lambda s: s.order)[:15], 1):
        lines.append(f"{i}. **{step.name}**: {step.description}\n")

    return "".join(lines)


def render_semantic_memory_pipeline() -> str:
    """Render the semantic memory pipeline diagram."""
    lines = [_banner()]
    lines.append("# Semantic Memory Pipeline\n\n")
    lines.append(
        "> Pipeline for storing and retrieving semantic memories with vector embeddings.\n\n"
    )

    lines.append("## Memory Pipeline Flow\n\n")
    lines.append("```mermaid\n")
    lines.append("graph LR\n")
    lines.append("    Input[User Input] --> Parser[Query Parser]\n")
    lines.append("    Parser --> Embedding[Embedding Generator]\n")
    lines.append("    Embedding --> Vector[Vector Store]\n")
    lines.append("    Vector --> Cache[Embedding Cache]\n")
    lines.append("    Cache --> Retrieval[Similarity Search]\n")
    lines.append("    Retrieval --> Ranker[Result Ranker]\n")
    lines.append("    Ranker --> Context[Context Builder]\n")
    lines.append("    Context --> Output[Enriched Context]\n\n")

    lines.append("    style Input fill:#ffd43b,stroke:#f08c00\n")
    lines.append("    style Embedding fill:#4dabf7,stroke:#1971c2\n")
    lines.append("    style Vector fill:#51cf66,stroke:#2f9e44\n")
    lines.append("    style Output fill:#ff6b6b,stroke:#c92a2a\n")
    lines.append("```\n\n")

    lines.append("## Pipeline Stages\n\n")
    lines.append("1. **Query Parser**: Extracts semantic intent from user query\n")
    lines.append("2. **Embedding Generator**: Converts query to vector representation\n")
    lines.append("3. **Vector Store**: Qdrant vector database for similarity search\n")
    lines.append("4. **Embedding Cache**: LRU cache for frequently accessed embeddings\n")
    lines.append("5. **Similarity Search**: K-nearest neighbors retrieval\n")
    lines.append("6. **Result Ranker**: Reranks results by relevance and recency\n")
    lines.append("7. **Context Builder**: Assembles final context from retrieved memories\n")

    return "".join(lines)


def render_hybrid_retrieval_pipeline() -> str:
    """Render the hybrid retrieval pipeline diagram."""
    lines = [_banner()]
    lines.append("# Hybrid Retrieval Pipeline\n\n")
    lines.append("> Combined keyword and semantic search for comprehensive memory retrieval.\n\n")

    lines.append("## Hybrid Retrieval Flow\n\n")
    lines.append("```mermaid\n")
    lines.append("graph TB\n")
    lines.append("    Query[User Query]\n")
    lines.append("    Query --> KeywordPath[Keyword Search]\n")
    lines.append("    Query --> SemanticPath[Semantic Search]\n\n")

    lines.append("    KeywordPath --> FTS[Full-Text Search]\n")
    lines.append("    FTS --> KeywordResults[Keyword Results]\n\n")

    lines.append("    SemanticPath --> Embed[Generate Embedding]\n")
    lines.append("    Embed --> VectorSearch[Vector Similarity]\n")
    lines.append("    VectorSearch --> SemanticResults[Semantic Results]\n\n")

    lines.append("    KeywordResults --> Merger[Result Merger]\n")
    lines.append("    SemanticResults --> Merger\n")
    lines.append("    Merger --> Dedup[Deduplication]\n")
    lines.append("    Dedup --> Rerank[Hybrid Reranker]\n")
    lines.append("    Rerank --> Final[Final Results]\n\n")

    lines.append("    style KeywordPath fill:#4dabf7,stroke:#1971c2\n")
    lines.append("    style SemanticPath fill:#51cf66,stroke:#2f9e44\n")
    lines.append("    style Merger fill:#ffd43b,stroke:#f08c00\n")
    lines.append("    style Final fill:#ff6b6b,stroke:#c92a2a\n")
    lines.append("```\n\n")

    lines.append("## Retrieval Strategies\n\n")
    lines.append("### Keyword Search Path\n")
    lines.append("- Full-text search on conversation history\n")
    lines.append("- Exact and fuzzy matching\n")
    lines.append("- Fast for known terms and entities\n\n")

    lines.append("### Semantic Search Path\n")
    lines.append("- Vector embedding similarity\n")
    lines.append("- Captures semantic meaning\n")
    lines.append("- Finds conceptually related content\n\n")

    lines.append("### Hybrid Combination\n")
    lines.append("- Merges results from both paths\n")
    lines.append("- Removes duplicates\n")
    lines.append("- Reranks by combined relevance score\n")

    return "".join(lines)


def render_persistence_architecture(layers: List[PersistenceLayer]) -> str:
    """Render the persistence architecture diagram."""
    lines = [_banner()]
    lines.append("# Persistence Architecture\n\n")
    lines.append("> Multi-layer persistence architecture with SQL, NoSQL, and vector stores.\n\n")

    lines.append("## Persistence Layers\n\n")
    lines.append("```mermaid\n")
    lines.append("graph TB\n")
    lines.append("    App[Application Layer]\n")
    lines.append("    App --> PersistenceService[Persistence Service]\n\n")

    lines.append("    PersistenceService --> SQLite[SQLite]\n")
    lines.append("    PersistenceService --> PostgreSQL[PostgreSQL]\n")
    lines.append("    PersistenceService --> Redis[Redis]\n")
    lines.append("    PersistenceService --> Qdrant[Qdrant]\n\n")

    lines.append("    SQLite --> SQLiteRepos[Local Development<br/>Workspaces, Projects]\n")
    lines.append("    PostgreSQL --> PostgresRepos[Production Data<br/>Users, Sessions, Logs]\n")
    lines.append("    Redis --> RedisData[Ephemeral Data<br/>Cache, Sessions]\n")
    lines.append("    Qdrant --> QdrantData[Vector Data<br/>Embeddings, Memories]\n\n")

    lines.append("    style PersistenceService fill:#ffd43b,stroke:#f08c00,stroke-width:3px\n")
    lines.append("    style SQLite fill:#4dabf7,stroke:#1971c2\n")
    lines.append("    style PostgreSQL fill:#4dabf7,stroke:#1971c2\n")
    lines.append("    style Redis fill:#51cf66,stroke:#2f9e44\n")
    lines.append("    style Qdrant fill:#ff6b6b,stroke:#c92a2a\n")
    lines.append("```\n\n")

    lines.append("## Storage Layer Details\n\n")
    for layer in layers:
        lines.append(f"### {layer.name} ({layer.type.upper()})\n\n")
        lines.append(f"**Purpose**: {layer.purpose}\n\n")
        if layer.repositories:
            lines.append(f"**Repositories**: {len(layer.repositories)}\n\n")

    return "".join(lines)


def render_omniroute_architecture() -> str:
    """Render the OmniRoute model selection architecture."""
    lines = [_banner()]
    lines.append("# OmniRoute Architecture\n\n")
    lines.append(
        "> Intelligent model selection and routing based on task complexity and capabilities.\n\n"
    )

    lines.append("## OmniRoute Decision Flow\n\n")
    lines.append("```mermaid\n")
    lines.append("graph TB\n")
    lines.append("    Request[User Request] --> Analyzer[Request Analyzer]\n")
    lines.append("    Analyzer --> Classifier[Task Classifier]\n\n")

    lines.append("    Classifier --> CodeTask{Code Task?}\n")
    lines.append("    Classifier --> ReasonTask{Complex Reasoning?}\n")
    lines.append("    Classifier --> ChatTask{Simple Chat?}\n\n")

    lines.append("    CodeTask -->|Yes| Claude[Claude Sonnet]\n")
    lines.append("    ReasonTask -->|Yes| GPT4[GPT-4o]\n")
    lines.append("    ChatTask -->|Yes| Gemini[Gemini Pro]\n\n")

    lines.append("    Claude --> Router[Model Router]\n")
    lines.append("    GPT4 --> Router\n")
    lines.append("    Gemini --> Router\n\n")

    lines.append("    Router --> Fallback{Primary Available?}\n")
    lines.append("    Fallback -->|Yes| Primary[Route to Primary]\n")
    lines.append("    Fallback -->|No| Secondary[Route to Fallback]\n\n")

    lines.append("    Primary --> Response[Generate Response]\n")
    lines.append("    Secondary --> Response\n\n")

    lines.append("    style Analyzer fill:#ffd43b,stroke:#f08c00\n")
    lines.append("    style Claude fill:#4dabf7,stroke:#1971c2\n")
    lines.append("    style GPT4 fill:#51cf66,stroke:#2f9e44\n")
    lines.append("    style Gemini fill:#ff6b6b,stroke:#c92a2a\n")
    lines.append("```\n\n")

    lines.append("## Model Selection Criteria\n\n")
    lines.append("### Task Classification\n")
    lines.append("- **Code Generation/Analysis**: Claude Sonnet (primary)\n")
    lines.append("- **Complex Reasoning**: GPT-4o (primary)\n")
    lines.append("- **Simple Chat/Q&A**: Gemini Pro (cost-effective)\n")
    lines.append("- **Specialized Tasks**: Task-specific model selection\n\n")

    lines.append("### Fallback Strategy\n")
    lines.append("- Primary model unavailable → fallback to secondary\n")
    lines.append("- Rate limit exceeded → queue or fallback\n")
    lines.append("- Quality monitoring → switch if quality degrades\n")

    return "".join(lines)


def render_agent_interaction_flow() -> str:
    """Render the agent interaction and coordination flow."""
    lines = [_banner()]
    lines.append("# Agent Interaction Flow\n\n")
    lines.append("> Multi-agent coordination and communication patterns.\n\n")

    lines.append("## Agent Coordination Flow\n\n")
    lines.append("```mermaid\n")
    lines.append("sequenceDiagram\n")
    lines.append("    participant User\n")
    lines.append("    participant Career\n")
    lines.append("    participant Developer\n")
    lines.append("    participant Memory\n")
    lines.append("    participant Task\n\n")

    lines.append("    User->>Career: Career goal request\n")
    lines.append("    Career->>Memory: Retrieve career history\n")
    lines.append("    Memory-->>Career: Past achievements\n")
    lines.append("    Career->>Task: Create career tasks\n")
    lines.append("    Task-->>Career: Task plan\n")
    lines.append("    Career-->>User: Career roadmap\n\n")

    lines.append("    User->>Developer: Code implementation request\n")
    lines.append("    Developer->>Memory: Retrieve codebase context\n")
    lines.append("    Memory-->>Developer: Relevant code snippets\n")
    lines.append("    Developer->>Task: Create implementation tasks\n")
    lines.append("    Task->>Developer: Task breakdown\n")
    lines.append("    Developer->>Developer: Execute tasks\n")
    lines.append("    Developer-->>User: Implementation complete\n")
    lines.append("```\n\n")

    lines.append("## Agent Capabilities\n\n")
    lines.append("### Career Agent\n")
    lines.append("- Career planning and goal setting\n")
    lines.append("- Interview preparation\n")
    lines.append("- Resume optimization\n")
    lines.append("- Learning path recommendations\n\n")

    lines.append("### Developer Agent\n")
    lines.append("- Code generation and analysis\n")
    lines.append("- Bug fixing and debugging\n")
    lines.append("- Refactoring and optimization\n")
    lines.append("- Testing and documentation\n\n")

    lines.append("### Memory Agent\n")
    lines.append("- Context retrieval\n")
    lines.append("- Semantic search\n")
    lines.append("- Knowledge base queries\n")
    lines.append("- Conversation history\n\n")

    lines.append("### Task Agent\n")
    lines.append("- Task decomposition\n")
    lines.append("- Execution planning\n")
    lines.append("- Progress tracking\n")
    lines.append("- Dependency management\n")

    return "".join(lines)


def render_diagrams_index(diagram_count: int) -> str:
    """Render the README index for diagram documentation."""
    lines = [_banner()]
    lines.append("# Architecture Diagrams\n\n")
    lines.append("> Auto-generated Mermaid diagrams for system architecture visualization.\n\n")

    now = datetime.datetime.now(datetime.UTC).strftime(_TIMESTAMP_FMT)
    lines.append(f"**Generated**: {now}\n\n")

    lines.append("## Overview\n\n")
    lines.append(f"This directory contains {diagram_count} Mermaid architecture diagrams ")
    lines.append("that visualize different aspects of the AI OS system.\n\n")

    lines.append("## Diagram Files\n\n")
    lines.append("| File | Description |\n")
    lines.append("|------|-------------|\n")
    lines.append(
        "| [architecture.md](architecture.md) | Overall AI OS architecture with component relationships |\n"
    )
    lines.append("| [dependency_graph.md](dependency_graph.md) | Service dependency graph |\n")
    lines.append("| [lifecycle.md](lifecycle.md) | Runtime lifecycle phases and transitions |\n")
    lines.append("| [runtime.md](runtime.md) | Bootstrap sequence and initialization flow |\n")
    lines.append("| [persistence.md](persistence.md) | Multi-layer persistence architecture |\n")
    lines.append(
        "| [semantic_memory.md](semantic_memory.md) | Semantic memory pipeline with vector embeddings |\n"
    )
    lines.append(
        "| [hybrid_retrieval.md](hybrid_retrieval.md) | Hybrid keyword and semantic retrieval |\n"
    )
    lines.append("| [omniroute.md](omniroute.md) | OmniRoute model selection and routing |\n")
    lines.append("| [agents.md](agents.md) | Agent interaction and coordination flow |\n\n")

    lines.append("## Viewing Diagrams\n\n")
    lines.append("These diagrams use Mermaid syntax and can be viewed in:\n\n")
    lines.append("- GitHub (native Mermaid rendering)\n")
    lines.append("- VS Code (with Mermaid extension)\n")
    lines.append("- Mermaid Live Editor (https://mermaid.live)\n")
    lines.append("- Any Markdown renderer with Mermaid support\n\n")

    lines.append("## Regeneration\n\n")
    lines.append("To regenerate these diagrams:\n\n")
    lines.append("```bash\n")
    lines.append("python -m aios.docgen.diagram_main\n")
    lines.append("```\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [Generated Documentation](../generated/README.md) - Component catalogs\n")
    lines.append(
        "- [API & Service Reference](../reference/README.md) - Detailed API documentation\n"
    )
    lines.append(
        "- [Architecture Documentation](../architecture/README.md) - System design documents\n"
    )

    return "".join(lines)
