"""
ops_renderers.py — Renderers for deployment and operations guides.

Produces operational documentation in Markdown format.
All content is derived deterministically from analyzed data.
"""

from __future__ import annotations

import datetime
from typing import List

from aios.docgen.ops_models import (
    BackupTarget,
    ConfigurationItem,
    MonitoringMetric,
    OmniRouteProvider,
    ServiceDeployment,
    StartupStep,
    TroubleshootingEntry,
)

_TIMESTAMP_FMT = "%Y-%m-%dT%H:%M:%SZ"


def _banner() -> str:
    """Generate the auto-generated warning banner."""
    now = datetime.datetime.now(datetime.UTC).strftime(_TIMESTAMP_FMT)
    return f"""<!--
  ⚠  AUTO-GENERATED — DO NOT EDIT MANUALLY
  Generated by: aios.docgen operations guide generator
  Generated on: {now}
  This file is recreated on every generation run.
  Edit the source code and re-run the generator to update this file.
-->

"""


def render_readme_index(guide_count: int) -> str:
    """Render the README index for operations documentation."""
    lines = [_banner()]
    lines.append("# Deployment & Operations Guides\n\n")
    lines.append("> Operational documentation for deployment, configuration, and maintenance.\n\n")

    now = datetime.datetime.now(datetime.UTC).strftime(_TIMESTAMP_FMT)
    lines.append(f"**Generated**: {now}\n\n")

    lines.append("## Overview\n\n")
    lines.append(f"This directory contains {guide_count} operational guides covering deployment, ")
    lines.append("configuration, monitoring, and troubleshooting for the AI OS.\n\n")

    lines.append("## Guide Files\n\n")
    lines.append("| File | Description |\n")
    lines.append("|------|-------------|\n")
    lines.append("| [local_setup.md](local_setup.md) | Local development environment setup |\n")
    lines.append("| [configuration.md](configuration.md) | Environment and service configuration |\n")
    lines.append("| [deployment.md](deployment.md) | Production deployment procedures |\n")
    lines.append("| [startup.md](startup.md) | Service startup order and dependencies |\n")
    lines.append("| [monitoring.md](monitoring.md) | Monitoring metrics and alerts |\n")
    lines.append("| [backup_restore.md](backup_restore.md) | Backup and restore procedures |\n")
    lines.append("| [troubleshooting.md](troubleshooting.md) | Common issues and solutions |\n")
    lines.append("| [production_checklist.md](production_checklist.md) | Pre-deployment checklist |\n\n")

    lines.append("## Regeneration\n\n")
    lines.append("To regenerate these guides:\n\n")
    lines.append("```bash\n")
    lines.append("python -m aios.docgen.ops_main\n")
    lines.append("```\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [Generated Documentation](../generated/README.md) - Component catalogs\n")
    lines.append("- [API & Service Reference](../reference/README.md) - Detailed API documentation\n")
    lines.append("- [Architecture Diagrams](../diagrams/README.md) - System architecture visualizations\n")

    return "".join(lines)


def render_local_setup(deployments: List[ServiceDeployment]) -> str:
    """Render the local development setup guide."""
    lines = [_banner()]
    lines.append("# Local Development Setup\n\n")
    lines.append("> Step-by-step guide for setting up a local development environment.\n\n")

    lines.append("## Prerequisites\n\n")
    lines.append("- Python 3.10 or higher\n")
    lines.append("- Docker and Docker Compose\n")
    lines.append("- Git\n")
    lines.append("- 8 GB RAM minimum (16 GB recommended)\n")
    lines.append("- 20 GB disk space minimum\n\n")

    lines.append("## Installation Steps\n\n")

    lines.append("### 1. Clone Repository\n\n")
    lines.append("```bash\n")
    lines.append("git clone https://github.com/your-org/aios.git\n")
    lines.append("cd aios\n")
    lines.append("```\n\n")

    lines.append("### 2. Create Virtual Environment & Install Dependencies\n\n")
    lines.append("```bash\n")
    lines.append("python3 -m venv .venv\n")
    lines.append("source .venv/bin/activate  # Linux/macOS\n")
    lines.append("# .venv\\Scripts\\activate  # Windows\n")
    lines.append("pip install -e ./core\n")
    lines.append("```\n\n")

    lines.append("### 3. Start External Services\n\n")
    lines.append("Start required external services using Docker Compose:\n\n")
    lines.append("```bash\n")
    lines.append("docker-compose up -d postgres redis qdrant\n")
    lines.append("```\n\n")

    external_services = [d for d in deployments if d.type == "external" and d.required]
    if external_services:
        lines.append("**Required services:**\n\n")
        lines.append("| Service | Default Port | Purpose |\n")
        lines.append("|---------|-------------|----------|\n")
        for service in external_services:
            port_str = str(service.port) if service.port else "—"
            purpose = {
                "PostgreSQL": "SQL persistence — workspaces, tasks, AI memory",
                "Redis": "Cache, sessions, distributed locks, queues, rate limiting",
                "Qdrant": "Vector store — semantic memory, conversation embeddings",
            }.get(service.name, "Platform service")
            lines.append(f"| {service.name} | {port_str} | {purpose} |\n")
        lines.append("\n")

    lines.append("**Optional services:**\n\n")
    optional = [d for d in deployments if not d.required and d.type == "external"]
    for svc in optional:
        port_str = f" (port {svc.port})" if svc.port else ""
        lines.append(f"- **{svc.name}**{port_str} — workflow automation (`docker-compose up -d n8n`)\n")
    lines.append("\n")

    lines.append("### 4. Configure Environment\n\n")
    lines.append("Create a `.env` file with required configuration:\n\n")
    lines.append("```bash\n")
    lines.append("cp .env.example .env\n")
    lines.append("# Edit .env with your API keys and service addresses\n")
    lines.append("```\n\n")
    lines.append(
        "Minimum required variables for local development:\n\n"
        "```bash\n"
        "# PostgreSQL\n"
        "POSTGRES_HOST=localhost\n"
        "POSTGRES_PORT=5432\n"
        "POSTGRES_DATABASE=aios\n"
        "POSTGRES_USER=aios_user\n"
        "POSTGRES_PASSWORD=<your-password>\n\n"
        "# Redis\n"
        "REDIS_HOST=localhost\n"
        "REDIS_PORT=6379\n\n"
        "# Qdrant\n"
        "QDRANT_HOST=127.0.0.1\n"
        "QDRANT_PORT=6333\n\n"
        "# OmniRoute (at least one provider required)\n"
        "OPENROUTER_API_KEY=sk-or-...\n"
        "```\n\n"
    )
    lines.append("See [configuration.md](configuration.md) for all configuration parameters.\n\n")

    lines.append("### 5. Configure AIOS\n\n")
    lines.append("Review and edit `config/config.toml`:\n\n")
    lines.append("```toml\n")
    lines.append("[runtime]\n")
    lines.append('name = "Personal AI OS"\n')
    lines.append('version = "1.0.0"\n')
    lines.append("debug = false\n\n")
    lines.append("[llm]\n")
    lines.append('provider = "openrouter"\n')
    lines.append('default_model = "qwen/qwen3-coder"\n\n')
    lines.append("[llm.openrouter]\n")
    lines.append('base_url = "https://openrouter.ai/api/v1"\n')
    lines.append("timeout = 30\n")
    lines.append("```\n\n")

    lines.append("### 6. Run Database Migrations\n\n")
    lines.append(
        "Migrations are run automatically inside `bootstrap_kernel()` on startup. "
        "To run them manually:\n\n"
    )
    lines.append("```bash\n")
    lines.append("python -m aios.migrations\n")
    lines.append("```\n\n")

    lines.append("### 7. Start AIOS\n\n")
    lines.append("```bash\n")
    lines.append("aios\n")
    lines.append("```\n\n")

    lines.append("## Verification\n\n")
    lines.append("Verify your setup is working:\n\n")
    lines.append("```bash\n")
    lines.append("# 1. Check AIOS version\n")
    lines.append("aios --version\n\n")
    lines.append("# 2. Test PostgreSQL connectivity\n")
    lines.append("psql -U $POSTGRES_USER -d $POSTGRES_DATABASE -c 'SELECT version();'\n\n")
    lines.append("# 3. Test Redis connectivity\n")
    lines.append("redis-cli -h $REDIS_HOST -p $REDIS_PORT ping  # Expects: PONG\n\n")
    lines.append("# 4. Test Qdrant connectivity\n")
    lines.append("curl http://$QDRANT_HOST:$QDRANT_PORT/health\n")
    lines.append("```\n\n")

    lines.append("## Troubleshooting\n\n")
    lines.append("See [troubleshooting.md](troubleshooting.md) for common setup issues.\n")

    return "".join(lines)


def render_configuration(
    configs: List[ConfigurationItem],
    omniroute_providers: List[OmniRouteProvider],
) -> str:
    """Render the configuration guide."""
    lines = [_banner()]
    lines.append("# Configuration Guide\n\n")
    lines.append("> Complete configuration reference for all environment variables and settings.\n\n")

    lines.append("## Configuration Overview\n\n")
    lines.append("AIOS can be configured via:\n\n")
    lines.append("1. Environment variables (`.env` file or shell environment)\n")
    lines.append("2. Configuration file (`config/config.toml`)\n")
    lines.append("3. Command-line arguments\n\n")

    lines.append("**Priority order** (highest wins): CLI args > Environment variables > Config file > Defaults\n\n")

    lines.append("> **Security Note**: Never commit secrets to version control. ")
    lines.append("Use a secrets manager (AWS Secrets Manager, HashiCorp Vault, etc.) in production.\n\n")

    # ── Core ──────────────────────────────────────────────────────────────────
    core_configs = [c for c in configs if c.section == "core"]
    lines.append("## Core Configuration\n\n")
    lines.append("| Parameter | Description | Default | Required |\n")
    lines.append("|-----------|-------------|---------|----------|\n")
    for config in core_configs:
        req = "Yes" if config.required else "No"
        default = config.default or "—"
        lines.append(f"| `{config.key}` | {config.description} | {default} | {req} |\n")
    lines.append("\n")

    if core_configs:
        lines.append("**Example:**\n\n")
        lines.append("```bash\n")
        for config in core_configs:
            if config.example:
                lines.append(f"{config.env_var}={config.example}\n")
        lines.append("```\n\n")

    # ── PostgreSQL ────────────────────────────────────────────────────────────
    db_configs = [c for c in configs if c.section == "postgres"]
    lines.append("## PostgreSQL Configuration\n\n")
    lines.append(
        "> Sourced from: `core/src/aios/services/persistence.py` — "
        "`PersistenceConfigurationService`\n\n"
    )
    lines.append("| Parameter | Description | Default | Required |\n")
    lines.append("|-----------|-------------|---------|----------|\n")
    for config in db_configs:
        req = "Yes" if config.required else "No"
        default = config.default or "—"
        lines.append(f"| `{config.key}` | {config.description} | {default} | {req} |\n")
    lines.append("\n")

    lines.append("**Example:**\n\n")
    lines.append("```bash\n")
    lines.append("POSTGRES_HOST=localhost\n")
    lines.append("POSTGRES_PORT=5432\n")
    lines.append("POSTGRES_DATABASE=aios\n")
    lines.append("POSTGRES_USER=aios_user\n")
    lines.append("POSTGRES_PASSWORD=<secure-password>\n")
    lines.append("POSTGRES_SSLMODE=require  # Use 'require' in production\n")
    lines.append("POSTGRES_CONNECT_TIMEOUT=10\n")
    lines.append("```\n\n")

    lines.append(
        "> **Note**: `POSTGRES_DATABASE` is the canonical variable name used in the implementation. "
        "`POSTGRES_DB` is also accepted for backward compatibility.\n\n"
    )

    # ── Redis ─────────────────────────────────────────────────────────────────
    redis_configs = [c for c in configs if c.section == "redis"]
    lines.append("## Redis Configuration\n\n")
    lines.append(
        "> Sourced from: `core/src/aios/services/persistence_impl_modules/redis.py` — "
        "`RedisConfigurationService`\n\n"
    )
    lines.append("| Parameter | Description | Default | Required |\n")
    lines.append("|-----------|-------------|---------|----------|\n")
    for config in redis_configs:
        req = "Yes" if config.required else "No"
        default = config.default or "—"
        lines.append(f"| `{config.key}` | {config.description} | {default} | {req} |\n")
    lines.append("\n")

    lines.append("**Example:**\n\n")
    lines.append("```bash\n")
    lines.append("REDIS_HOST=localhost\n")
    lines.append("REDIS_PORT=6379\n")
    lines.append("REDIS_PASSWORD=<redis-password>     # optional but recommended\n")
    lines.append("REDIS_DATABASE=0\n")
    lines.append("REDIS_TLS=true                      # enable in production\n")
    lines.append("REDIS_TIMEOUT=5.0\n")
    lines.append("```\n\n")

    lines.append(
        "> **Redis Usage in AIOS**: Redis provides the Cache Platform, Session Store, "
        "Distributed Lock Manager, Queue Service, and Rate Limiter. "
        "All are initialized during bootstrap.\n\n"
    )

    # ── Qdrant ────────────────────────────────────────────────────────────────
    qdrant_configs = [c for c in configs if c.section == "qdrant"]
    lines.append("## Qdrant Configuration\n\n")
    lines.append(
        "> Sourced from: `core/src/aios/services/persistence_impl_modules/qdrant.py` — "
        "`QdrantConfigurationService`\n\n"
    )
    lines.append("| Parameter | Description | Default | Required |\n")
    lines.append("|-----------|-------------|---------|----------|\n")
    for config in qdrant_configs:
        req = "Yes" if config.required else "No"
        default = config.default or "—"
        lines.append(f"| `{config.key}` | {config.description} | {default} | {req} |\n")
    lines.append("\n")

    lines.append("**Example:**\n\n")
    lines.append("```bash\n")
    lines.append("QDRANT_HOST=127.0.0.1\n")
    lines.append("QDRANT_PORT=6333\n")
    lines.append("QDRANT_GRPC_PORT=6334              # for high-throughput vector ops\n")
    lines.append("QDRANT_API_KEY=<api-key>           # required for Qdrant Cloud\n")
    lines.append("QDRANT_HTTPS=true                  # enable for Qdrant Cloud\n")
    lines.append("QDRANT_TIMEOUT=10.0\n")
    lines.append("QDRANT_DEFAULT_DIMENSIONS=1536     # must match embedding model output\n")
    lines.append("QDRANT_DEFAULT_DISTANCE=COSINE\n")
    lines.append("```\n\n")

    lines.append(
        "> **Qdrant Collections**: AIOS creates and manages Qdrant collections automatically "
        "during bootstrap. The primary collection is `conversation_memory` used by the "
        "Runtime Intelligence Platform.\n\n"
    )

    # ── n8n ───────────────────────────────────────────────────────────────────
    n8n_configs = [c for c in configs if c.section == "n8n"]
    lines.append("## n8n (Optional) Configuration\n\n")
    lines.append(
        "> Sourced from: `core/src/aios/n8n/service.py` — `N8NConfigurationService`\n\n"
    )
    lines.append(
        "n8n is an optional workflow automation platform. "
        "If `N8N_SERVER_URL` is not set, the n8n platform registers in a disconnected state "
        "and AIOS runs normally without it.\n\n"
    )
    lines.append("| Parameter | Description | Default | Required |\n")
    lines.append("|-----------|-------------|---------|----------|\n")
    for config in n8n_configs:
        req = "Yes" if config.required else "No"
        default = config.default or "—"
        lines.append(f"| `{config.key}` | {config.description} | {default} | {req} |\n")
    lines.append("\n")

    lines.append("**Example (API key authentication — preferred):**\n\n")
    lines.append("```bash\n")
    lines.append("N8N_SERVER_URL=http://localhost:5678\n")
    lines.append("N8N_API_KEY=<your-n8n-api-key>\n")
    lines.append("```\n\n")

    lines.append("**Example (session-based authentication — fallback):**\n\n")
    lines.append("```bash\n")
    lines.append("N8N_SERVER_URL=http://localhost:5678\n")
    lines.append("N8N_EMAIL=admin@example.com\n")
    lines.append("N8N_PASSWORD=<n8n-password>\n")
    lines.append("```\n\n")

    lines.append(
        "> **Authentication Priority**: `N8N_API_KEY` → `N8N_BEARER_TOKEN` → "
        "`N8N_EMAIL` + `N8N_PASSWORD` (session cookie).\n\n"
    )
    lines.append(
        "See [Architecture Diagrams — OmniRoute](../diagrams/omniroute.md) for the "
        "n8n integration architecture.\n\n"
    )

    # ── OmniRoute ─────────────────────────────────────────────────────────────
    lines.append("## OmniRoute / AI Provider Configuration\n\n")
    lines.append(
        "> Sourced from: `core/src/aios/services/model_impl.py`, "
        "`core/src/aios/providers/registry.py`\n\n"
    )
    lines.append(
        "OmniRoute is the AIOS model selection and routing layer. "
        "It selects the optimal AI provider for each request based on capability, "
        "cost, and health. At least one provider API key must be configured.\n\n"
    )

    lines.append("| Provider | Environment Variable | Default Model | Notes |\n")
    lines.append("|----------|---------------------|--------------|-------|\n")
    for provider in omniroute_providers:
        req_str = "Required" if provider.required else "Optional"
        lines.append(
            f"| {provider.name} | `{provider.env_key}` | `{provider.default_model}` "
            f"| {req_str} |\n"
        )
    lines.append("\n")

    for provider in omniroute_providers:
        lines.append(f"**{provider.name}** — `{provider.env_key}`\n\n")
        lines.append(f"{provider.description}\n\n")
        lines.append(f"- Base URL: `{provider.base_url}`\n")
        lines.append(f"- Default model: `{provider.default_model}`\n\n")

    lines.append("**config/config.toml (OmniRoute defaults):**\n\n")
    lines.append("```toml\n")
    lines.append("[llm]\n")
    lines.append('provider = "openrouter"\n')
    lines.append('default_model = "qwen/qwen3-coder"\n\n')
    lines.append("[llm.openrouter]\n")
    lines.append('base_url = "https://openrouter.ai/api/v1"\n')
    lines.append("timeout = 30\n")
    lines.append("```\n\n")

    lines.append(
        "See [Architecture Diagrams — OmniRoute](../diagrams/omniroute.md) and "
        "[Generated — Providers](../generated/providers.md) for routing details.\n\n"
    )

    lines.append(
        "> **Security Note**: Store all API keys securely. "
        "Never commit them to version control. "
        "Use environment variables or a secrets manager in production.\n"
    )

    return "".join(lines)


def render_deployment(deployments: List[ServiceDeployment]) -> str:
    """Render the deployment guide."""
    lines = [_banner()]
    lines.append("# Deployment Guide\n\n")
    lines.append("> Production deployment procedures and best practices.\n\n")

    lines.append("## Deployment Architecture\n\n")
    lines.append("AIOS requires the following services in production:\n\n")

    required = [d for d in deployments if d.required]
    optional = [d for d in deployments if not d.required]

    lines.append("**Required Services:**\n\n")
    for service in required:
        port_str = f" (port {service.port})" if service.port else ""
        lines.append(f"- {service.name}{port_str}\n")
    lines.append("\n")

    if optional:
        lines.append("**Optional Services:**\n\n")
        for service in optional:
            port_str = f" (port {service.port})" if service.port else ""
            lines.append(f"- {service.name}{port_str}\n")
        lines.append("\n")

    lines.append("## Pre-Deployment Checklist\n\n")
    lines.append("See [production_checklist.md](production_checklist.md) for a complete pre-deployment checklist.\n\n")

    lines.append("## Deployment Steps\n\n")

    lines.append("### 1. Provision Infrastructure\n\n")
    lines.append("Provision cloud resources:\n\n")
    lines.append("- Application server (4 CPU, 16 GB RAM minimum)\n")
    lines.append("- PostgreSQL database (managed service recommended: AWS RDS, GCP Cloud SQL)\n")
    lines.append("- Redis instance (managed service recommended: AWS ElastiCache, Redis Cloud)\n")
    lines.append("- Qdrant vector database (Qdrant Cloud or self-hosted)\n")
    lines.append("- Load balancer (if horizontal scaling)\n\n")

    lines.append("### 2. Configure Networking\n\n")
    lines.append("Set up security groups and firewall rules:\n\n")
    lines.append("- Allow inbound on application port (typically 8000)\n")
    lines.append("- Allow outbound to PostgreSQL (port 5432), Redis (port 6379), Qdrant (port 6333)\n")
    lines.append("- Restrict admin/management ports (SSH to VPN/bastion only)\n")
    lines.append("- Enable TLS/SSL for all external connections\n\n")

    lines.append("### 3. Deploy External Services\n\n")
    lines.append("Deploy in dependency order (see [startup.md](startup.md)):\n\n")
    lines.append("```bash\n")
    lines.append("# Deploy PostgreSQL, Redis, Qdrant via cloud provider or Docker\n")
    lines.append("docker-compose -f docker-compose.prod.yml up -d postgres redis qdrant\n")
    lines.append("```\n\n")

    lines.append("### 4. Configure Environment\n\n")
    lines.append("Set all production environment variables. See [configuration.md](configuration.md).\n\n")
    lines.append("```bash\n")
    lines.append("# Required for production\n")
    lines.append("POSTGRES_HOST=<production-host>\n")
    lines.append("POSTGRES_DATABASE=aios_production\n")
    lines.append("POSTGRES_USER=aios\n")
    lines.append("POSTGRES_PASSWORD=<rotate-regularly>\n")
    lines.append("POSTGRES_SSLMODE=require\n")
    lines.append("REDIS_HOST=<production-redis-host>\n")
    lines.append("REDIS_PASSWORD=<redis-password>\n")
    lines.append("REDIS_TLS=true\n")
    lines.append("QDRANT_HOST=<production-qdrant-host>\n")
    lines.append("QDRANT_API_KEY=<qdrant-api-key>\n")
    lines.append("QDRANT_HTTPS=true\n")
    lines.append("OPENROUTER_API_KEY=<openrouter-key>\n")
    lines.append("```\n\n")

    lines.append("### 5. Run Database Migrations\n\n")
    lines.append("```bash\n")
    lines.append("python -m aios.migrations\n")
    lines.append("```\n\n")

    lines.append("### 6. Deploy Application\n\n")
    lines.append("```bash\n")
    lines.append("# Build and deploy AIOS\n")
    lines.append("./deploy.sh production\n")
    lines.append("```\n\n")

    lines.append("### 7. Verify Deployment\n\n")
    lines.append("Run smoke tests:\n\n")
    lines.append("```bash\n")
    lines.append("./scripts/smoke-tests.sh\n\n")
    lines.append("# Manual verification\n")
    lines.append("aios --version\n")
    lines.append("curl http://localhost:8000/health\n")
    lines.append("```\n\n")

    lines.append("## Post-Deployment\n\n")
    lines.append("1. Configure monitoring (see [monitoring.md](monitoring.md))\n")
    lines.append("2. Set up backup automation (see [backup_restore.md](backup_restore.md))\n")
    lines.append("3. Configure alerting rules in Prometheus\n")
    lines.append("4. Test n8n integration if using workflow automation\n")
    lines.append("5. Document any deployment-specific notes in the runbook\n\n")

    lines.append("## Rollback Procedure\n\n")
    lines.append("If deployment fails:\n\n")
    lines.append("1. Stop the new deployment immediately\n")
    lines.append("2. Restore the previous application version\n")
    lines.append("3. Rollback database migrations if schema changed: `python -m aios.migrations --rollback`\n")
    lines.append("4. Verify system health on all service health endpoints\n")
    lines.append("5. Update incident log and perform post-mortem\n")

    return "".join(lines)


def render_startup(steps: List[StartupStep]) -> str:
    """Render the startup sequence guide."""
    lines = [_banner()]
    lines.append("# Service Startup Guide\n\n")
    lines.append("> Correct service startup order and dependency management.\n\n")

    lines.append("## Bootstrap Architecture\n\n")
    lines.append(
        "The AIOS startup sequence is orchestrated by `bootstrap_kernel()` in\n"
        "`core/src/aios/bootstrap_modules/bootstrap_kernel.py`. "
        "The kernel constructs services in this order:\n\n"
    )
    lines.append("```\n")
    lines.append("1. ServiceRegistry + Config\n")
    lines.append("2. EventBus\n")
    lines.append("3. SQL Persistence Platform (→ requires PostgreSQL)\n")
    lines.append("4. Redis Platform (→ requires Redis)\n")
    lines.append("5. Qdrant/Vector Memory Platform (→ requires Qdrant)\n")
    lines.append("6. Runtime Services & Agents\n")
    lines.append("7. Source Control Platform\n")
    lines.append("8. n8n Platform (optional)\n")
    lines.append("9. Kernel instantiation\n")
    lines.append("```\n\n")

    lines.append("## Startup Sequence\n\n")
    lines.append("Start services in the following order to respect bootstrap dependencies:\n\n")

    for step in sorted(steps, key=lambda s: s.order):
        lines.append(f"### Step {step.order}: {step.service}\n\n")
        lines.append(f"{step.description}\n\n")
        lines.append("```bash\n")
        lines.append(f"{step.command}\n")
        lines.append("```\n\n")

        if step.wait_for:
            lines.append(f"**Depends on**: {', '.join(step.wait_for)}\n\n")

        if step.healthcheck:
            lines.append("**Health check:**\n\n")
            lines.append("```bash\n")
            lines.append(f"{step.healthcheck}\n")
            lines.append("```\n\n")

        if step.notes:
            lines.append(f"> {step.notes}\n\n")

    lines.append("## Automated Startup\n\n")
    lines.append("For production, use a process manager or orchestration tool:\n\n")
    lines.append("```bash\n")
    lines.append("# Start all services with Docker Compose\n")
    lines.append("docker-compose up -d\n\n")
    lines.append("# Or using systemd (AIOS service unit)\n")
    lines.append("systemctl start aios\n")
    lines.append("```\n\n")

    lines.append("## Shutdown Sequence\n\n")
    lines.append("Shutdown in reverse startup order to prevent data loss:\n\n")
    lines.append("```bash\n")
    lines.append("# 1. Stop AIOS Core gracefully\n")
    lines.append("systemctl stop aios\n\n")
    lines.append("# 2. Stop n8n (if running)\n")
    lines.append("docker-compose stop n8n\n\n")
    lines.append("# 3. Stop external services\n")
    lines.append("docker-compose stop qdrant redis postgres\n")
    lines.append("```\n\n")

    lines.append("## Startup Failures\n\n")
    lines.append("Common startup issues:\n\n")
    lines.append("- **PostgreSQL not ready**: Wait for PostgreSQL to accept connections before starting AIOS\n")
    lines.append("- **Redis connection refused**: Verify REDIS_HOST and REDIS_PORT; check if Redis requires authentication\n")
    lines.append("- **Qdrant health check fails**: Wait for Qdrant to initialize; check QDRANT_HOST\n")
    lines.append("- **Migration failure**: Run `python -m aios.migrations` manually to inspect errors\n")
    lines.append("- **Port already in use**: Check for conflicting services with `lsof -i :<port>`\n")
    lines.append("- **API key not configured**: Ensure at least one OmniRoute provider key is set\n\n")

    lines.append("See [troubleshooting.md](troubleshooting.md) for detailed solutions.\n")

    return "".join(lines)


def render_monitoring(metrics: List[MonitoringMetric]) -> str:
    """Render the monitoring guide."""
    lines = [_banner()]
    lines.append("# Monitoring Guide\n\n")
    lines.append("> Monitoring metrics, alerts, and observability.\n\n")

    lines.append("## Monitoring Overview\n\n")
    lines.append(
        "AIOS exposes metrics for monitoring system health, performance, and resource usage. "
        "The recommended monitoring stack is Prometheus + Grafana + Alertmanager + Loki.\n\n"
    )

    # Group metrics by source
    service_metrics = [m for m in metrics if m.source == "service"]
    database_metrics = [m for m in metrics if m.source == "database"]
    system_metrics = [m for m in metrics if m.source == "system"]

    lines.append("## Service Metrics\n\n")
    lines.append("| Metric | Description | Alert Threshold |\n")
    lines.append("|--------|-------------|------------------|\n")
    for metric in service_metrics:
        threshold = metric.alert_threshold or "N/A"
        lines.append(f"| {metric.name} | {metric.description} | {threshold} |\n")
    lines.append("\n")

    lines.append("## Database Metrics\n\n")
    lines.append("| Metric | Description | Alert Threshold |\n")
    lines.append("|--------|-------------|------------------|\n")
    for metric in database_metrics:
        threshold = metric.alert_threshold or "N/A"
        lines.append(f"| {metric.name} | {metric.description} | {threshold} |\n")
    lines.append("\n")

    lines.append("## System Metrics\n\n")
    lines.append("| Metric | Description | Alert Threshold |\n")
    lines.append("|--------|-------------|------------------|\n")
    for metric in system_metrics:
        threshold = metric.alert_threshold or "N/A"
        lines.append(f"| {metric.name} | {metric.description} | {threshold} |\n")
    lines.append("\n")

    lines.append("## Monitoring Stack\n\n")
    lines.append("Recommended monitoring tools:\n\n")
    lines.append("- **Prometheus**: Metrics collection and storage\n")
    lines.append("- **Grafana**: Metrics visualization and dashboards\n")
    lines.append("- **Alertmanager**: Alert routing and notifications\n")
    lines.append("- **Loki**: Log aggregation\n\n")

    lines.append("## Setting Up Monitoring\n\n")

    lines.append("### 1. Install Monitoring Stack\n\n")
    lines.append("```bash\n")
    lines.append("docker-compose -f docker-compose.monitoring.yml up -d\n")
    lines.append("```\n\n")

    lines.append("### 2. Configure Prometheus\n\n")
    lines.append("Add AIOS as a scrape target in `prometheus.yml`:\n\n")
    lines.append("```yaml\n")
    lines.append("scrape_configs:\n")
    lines.append("  - job_name: 'aios'\n")
    lines.append("    static_configs:\n")
    lines.append("      - targets: ['aios:8000']\n")
    lines.append("  - job_name: 'postgres'\n")
    lines.append("    static_configs:\n")
    lines.append("      - targets: ['postgres-exporter:9187']\n")
    lines.append("  - job_name: 'redis'\n")
    lines.append("    static_configs:\n")
    lines.append("      - targets: ['redis-exporter:9121']\n")
    lines.append("```\n\n")

    lines.append("### 3. Import Grafana Dashboards\n\n")
    lines.append("Import pre-built dashboards from `monitoring/grafana/dashboards/`.\n\n")

    lines.append("### 4. Configure Alerts\n\n")
    lines.append("Configure alerting rules in Prometheus and notification channels in Alertmanager.\n\n")

    lines.append("## Health Checks\n\n")
    lines.append("AIOS provides health check endpoints:\n\n")
    lines.append("| Endpoint | Description |\n")
    lines.append("|----------|-------------|\n")
    lines.append("| `/health` | Overall system health |\n")
    lines.append("| `/health/db` | PostgreSQL database connectivity |\n")
    lines.append("| `/health/redis` | Redis connectivity and memory |\n")
    lines.append("| `/health/qdrant` | Qdrant connectivity and collection status |\n")
    lines.append("| `/health/n8n` | n8n server connectivity (if configured) |\n\n")

    lines.append("**Quick health check commands:**\n\n")
    lines.append("```bash\n")
    lines.append("# PostgreSQL\n")
    lines.append("psql -U $POSTGRES_USER -d $POSTGRES_DATABASE -c 'SELECT 1;'\n\n")
    lines.append("# Redis\n")
    lines.append("redis-cli -h $REDIS_HOST -p $REDIS_PORT ping\n\n")
    lines.append("# Qdrant\n")
    lines.append("curl http://$QDRANT_HOST:$QDRANT_PORT/health\n\n")
    lines.append("# n8n (if configured)\n")
    lines.append("curl $N8N_SERVER_URL/healthz\n")
    lines.append("```\n\n")

    lines.append("## Log Management\n\n")
    lines.append("Logs are written to:\n\n")
    lines.append("- **Application logs**: `$AIOS_HOME/logs/aios.log`\n")
    lines.append("- **Error logs**: `$AIOS_HOME/logs/error.log`\n")
    lines.append("- **Access logs**: `$AIOS_HOME/logs/access.log`\n\n")

    lines.append("Configure log retention and rotation using logrotate or your logging platform.\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [Reference — Services](../reference/services.md) — Service health APIs\n")
    lines.append("- [Generated — Runtime](../generated/runtime.md) — Runtime component catalog\n")
    lines.append("- [Diagrams — Architecture](../diagrams/architecture.md) — System overview\n")

    return "".join(lines)


def render_backup_restore(targets: List[BackupTarget]) -> str:
    """Render the backup and restore guide."""
    lines = [_banner()]
    lines.append("# Backup & Restore Guide\n\n")
    lines.append("> Procedures for backing up and restoring AIOS data.\n\n")

    lines.append("## Backup Strategy\n\n")
    lines.append("AIOS requires backing up the following components:\n\n")

    lines.append("| Component | Type | Frequency | Retention | Tool |\n")
    lines.append("|-----------|------|-----------|-----------|------|\n")
    for target in targets:
        lines.append(
            f"| {target.name} | {target.type} | {target.frequency} "
            f"| {target.retention} | {target.tool} |\n"
        )
    lines.append("\n")

    for target in targets:
        lines.append(f"### {target.name}\n\n")
        lines.append(f"- **Type**: {target.type}\n")
        lines.append(f"- **Backup location**: `{target.location}`\n")
        lines.append(f"- **Frequency**: {target.frequency}\n")
        lines.append(f"- **Retention**: {target.retention}\n")
        lines.append(f"- **Tool**: {target.tool}\n")
        if target.notes:
            lines.append(f"- **Notes**: {target.notes}\n")
        lines.append("\n")

    lines.append("## Backup Procedures\n\n")

    lines.append("### PostgreSQL Backup\n\n")
    lines.append("**Manual backup:**\n\n")
    lines.append("```bash\n")
    lines.append(
        "pg_dump -U $POSTGRES_USER -d $POSTGRES_DATABASE -F c \\\n"
        "  -f /var/backups/aios/postgres/aios_$(date +%Y%m%d_%H%M%S).dump\n"
    )
    lines.append("```\n\n")

    lines.append("**Automated backup (cron — runs at 02:00 daily):**\n\n")
    lines.append("```bash\n")
    lines.append("0 2 * * * /opt/aios/scripts/backup-postgres.sh\n")
    lines.append("```\n\n")

    lines.append("**Verify backup integrity:**\n\n")
    lines.append("```bash\n")
    lines.append("pg_restore --list /var/backups/aios/postgres/aios_20260706_020000.dump | head -20\n")
    lines.append("```\n\n")

    lines.append("### Qdrant Backup\n\n")
    lines.append(
        "> Qdrant collections used by AIOS include `conversation_memory` and other "
        "runtime intelligence collections.\n\n"
    )
    lines.append("**Create snapshot:**\n\n")
    lines.append("```bash\n")
    lines.append(
        "curl -X POST http://$QDRANT_HOST:$QDRANT_PORT/collections/conversation_memory/snapshots\n"
    )
    lines.append("```\n\n")

    lines.append("**Download snapshot:**\n\n")
    lines.append("```bash\n")
    lines.append(
        "curl http://$QDRANT_HOST:$QDRANT_PORT/collections/conversation_memory/snapshots/{snapshot_name} \\\n"
        "  -o /var/backups/aios/qdrant/conversation_memory_$(date +%Y%m%d).snapshot\n"
    )
    lines.append("```\n\n")

    lines.append("**List existing snapshots:**\n\n")
    lines.append("```bash\n")
    lines.append(
        "curl http://$QDRANT_HOST:$QDRANT_PORT/collections/conversation_memory/snapshots\n"
    )
    lines.append("```\n\n")

    lines.append("### Configuration Backup\n\n")
    lines.append("**Backup configuration files (never include secret values in the archive):**\n\n")
    lines.append("```bash\n")
    lines.append(
        "tar -czf /var/backups/aios/config/config_$(date +%Y%m%d).tar.gz \\\n"
        "  config/config.toml docker-compose.yml docker-compose.prod.yml\n"
        "# Secrets (.env) are stored separately in a secrets manager\n"
    )
    lines.append("```\n\n")

    lines.append("## Restore Procedures\n\n")

    lines.append("### PostgreSQL Restore\n\n")
    lines.append("```bash\n")
    lines.append("# Stop AIOS Core first\n")
    lines.append("systemctl stop aios\n\n")
    lines.append("# Drop and recreate the database\n")
    lines.append("dropdb -U $POSTGRES_USER $POSTGRES_DATABASE\n")
    lines.append("createdb -U $POSTGRES_USER $POSTGRES_DATABASE\n\n")
    lines.append("# Restore from backup\n")
    lines.append(
        "pg_restore -U $POSTGRES_USER -d $POSTGRES_DATABASE \\\n"
        "  /var/backups/aios/postgres/aios_20260706_020000.dump\n"
    )
    lines.append("```\n\n")

    lines.append("### Qdrant Restore\n\n")
    lines.append("```bash\n")
    lines.append("# Upload snapshot to Qdrant\n")
    lines.append(
        "curl -X POST http://$QDRANT_HOST:$QDRANT_PORT/collections/conversation_memory/snapshots/upload \\\n"
        "  --data-binary @/var/backups/aios/qdrant/conversation_memory_20260706.snapshot\n\n"
    )
    lines.append("# Recover the collection from the uploaded snapshot\n")
    lines.append(
        'curl -X PUT http://$QDRANT_HOST:$QDRANT_PORT/collections/conversation_memory/snapshots/recover \\\n'
        '  -H \'Content-Type: application/json\' \\\n'
        '  -d \'{"location": "http://$QDRANT_HOST:$QDRANT_PORT/collections/conversation_memory/snapshots/{snapshot_name}"}\'\n'
    )
    lines.append("```\n\n")

    lines.append("### Configuration Restore\n\n")
    lines.append("```bash\n")
    lines.append("tar -xzf /var/backups/aios/config/config_20260706.tar.gz -C /opt/aios/\n")
    lines.append("# Restore secrets from your secrets manager separately\n")
    lines.append("```\n\n")

    lines.append("## Disaster Recovery\n\n")
    lines.append("In case of complete system failure:\n\n")
    lines.append("1. Provision new infrastructure (see [deployment.md](deployment.md))\n")
    lines.append("2. Install AIOS from source or deployment package\n")
    lines.append("3. Restore configuration files and secrets\n")
    lines.append("4. Restore PostgreSQL database from latest backup\n")
    lines.append("5. Restore Qdrant vector collections from snapshots\n")
    lines.append("6. Run database migrations to verify schema integrity\n")
    lines.append("7. Start services in correct order (see [startup.md](startup.md))\n")
    lines.append("8. Verify system health and resume monitoring\n\n")

    lines.append("**Estimated Recovery Time Objective (RTO)**: 2–4 hours\n")
    lines.append("**Recovery Point Objective (RPO)**: 24 hours (daily backups)\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [startup.md](startup.md) — Service startup order for restore\n")
    lines.append("- [production_checklist.md](production_checklist.md) — Post-restore verification\n")
    lines.append("- [monitoring.md](monitoring.md) — Monitor system health after restore\n")

    return "".join(lines)


def render_troubleshooting(entries: List[TroubleshootingEntry]) -> str:
    """Render the troubleshooting guide."""
    lines = [_banner()]
    lines.append("# Troubleshooting Guide\n\n")
    lines.append("> Common issues, root causes, and step-by-step solutions.\n\n")

    lines.append("## Quick Diagnostics\n\n")
    lines.append("Run these commands first to establish baseline status:\n\n")
    lines.append("```bash\n")
    lines.append("# AIOS status\n")
    lines.append("systemctl status aios\n\n")
    lines.append("# PostgreSQL\n")
    lines.append("psql -U $POSTGRES_USER -d $POSTGRES_DATABASE -c 'SELECT version();'\n\n")
    lines.append("# Redis\n")
    lines.append("redis-cli -h $REDIS_HOST -p $REDIS_PORT ping\n\n")
    lines.append("# Qdrant\n")
    lines.append("curl http://$QDRANT_HOST:$QDRANT_PORT/health\n\n")
    lines.append("# n8n (if configured)\n")
    lines.append("curl $N8N_SERVER_URL/healthz\n\n")
    lines.append("# Recent AIOS logs\n")
    lines.append("tail -100 $AIOS_HOME/logs/aios.log\n")
    lines.append("```\n\n")

    lines.append("## Common Issues\n\n")

    for i, entry in enumerate(entries, 1):
        lines.append(f"### Issue {i}: {entry.symptom}\n\n")
        lines.append(f"**Root Cause**: {entry.cause}\n\n")
        lines.append("**Solution**:\n\n")
        lines.append(f"{entry.solution}\n\n")

        if entry.related_logs:
            lines.append("**Related logs**:\n\n")
            for log in entry.related_logs:
                lines.append(f"- `{log}`\n")
            lines.append("\n")

        if entry.cross_refs:
            lines.append("**See also**:\n\n")
            for ref in entry.cross_refs:
                lines.append(f"- [{ref}]({ref})\n")
            lines.append("\n")

        lines.append("---\n\n")

    lines.append("## General Troubleshooting Steps\n\n")
    lines.append("1. **Check logs**: Review `$AIOS_HOME/logs/aios.log` and service-specific logs\n")
    lines.append("2. **Verify configuration**: Confirm all required environment variables are set\n")
    lines.append("3. **Test connectivity**: Verify each service responds to its health check\n")
    lines.append("4. **Check resources**: Monitor CPU, memory, and disk with `top`, `free`, `df -h`\n")
    lines.append("5. **Review recent changes**: `git log --oneline -20` for recent deployments\n")
    lines.append("6. **Restart in order**: Stop AIOS Core, then restart services per [startup.md](startup.md)\n\n")

    lines.append("## Diagnostic Commands\n\n")
    lines.append("```bash\n")
    lines.append("# Check AIOS process status\n")
    lines.append("systemctl status aios\n\n")
    lines.append("# Stream AIOS logs\n")
    lines.append("tail -f $AIOS_HOME/logs/aios.log\n\n")
    lines.append("# PostgreSQL — connectivity and version\n")
    lines.append("psql -U $POSTGRES_USER -d $POSTGRES_DATABASE -c 'SELECT version();'\n\n")
    lines.append("# PostgreSQL — active connections\n")
    lines.append("psql -U $POSTGRES_USER -d $POSTGRES_DATABASE \\\n")
    lines.append("  -c \"SELECT count(*) FROM pg_stat_activity WHERE state = 'active';\"\n\n")
    lines.append("# Redis — ping and memory info\n")
    lines.append("redis-cli -h $REDIS_HOST -p $REDIS_PORT ping\n")
    lines.append("redis-cli -h $REDIS_HOST -p $REDIS_PORT info memory | grep used_memory_human\n\n")
    lines.append("# Qdrant — health and collections\n")
    lines.append("curl http://$QDRANT_HOST:$QDRANT_PORT/health\n")
    lines.append("curl http://$QDRANT_HOST:$QDRANT_PORT/collections\n\n")
    lines.append("# Docker service status\n")
    lines.append("docker-compose ps\n")
    lines.append("docker-compose logs --tail=100 postgres\n")
    lines.append("docker-compose logs --tail=100 redis\n")
    lines.append("docker-compose logs --tail=100 qdrant\n")
    lines.append("```\n\n")

    lines.append("## Getting Help\n\n")
    lines.append("If you cannot resolve an issue:\n\n")
    lines.append("1. Gather diagnostic information (logs, configuration, error messages, system metrics)\n")
    lines.append("2. Search existing GitHub issues for similar symptoms\n")
    lines.append("3. Open a new issue with:\n")
    lines.append("   - AIOS version (`aios --version`)\n")
    lines.append("   - OS and Python version\n")
    lines.append("   - Exact error message and relevant log lines\n")
    lines.append("   - Steps to reproduce\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [configuration.md](configuration.md) — Verify all environment variables\n")
    lines.append("- [startup.md](startup.md) — Correct startup order\n")
    lines.append("- [monitoring.md](monitoring.md) — Health check endpoints\n")
    lines.append("- [Generated — Services](../generated/services.md) — Service implementation catalog\n")
    lines.append("- [Reference — Services](../reference/services.md) — Service API reference\n")

    return "".join(lines)


def render_production_checklist() -> str:
    """Render the production deployment checklist."""
    lines = [_banner()]
    lines.append("# Production Deployment Checklist\n\n")
    lines.append("> Pre-deployment verification checklist for production environments.\n\n")

    lines.append("## Infrastructure\n\n")
    lines.append("- [ ] Application servers provisioned (4 CPU, 16 GB RAM minimum per instance)\n")
    lines.append("- [ ] PostgreSQL database provisioned and accessible\n")
    lines.append("- [ ] Redis instance provisioned and accessible\n")
    lines.append("- [ ] Qdrant vector database provisioned and accessible\n")
    lines.append("- [ ] Load balancer configured (if horizontal scaling)\n")
    lines.append("- [ ] SSL/TLS certificates installed and valid (check expiry)\n")
    lines.append("- [ ] DNS records configured and propagated\n")
    lines.append("- [ ] Network firewall rules configured\n\n")

    lines.append("## Security\n\n")
    lines.append("- [ ] All secrets stored in a secrets manager (not in code or unencrypted files)\n")
    lines.append("- [ ] POSTGRES_PASSWORD is strong and unique (rotated regularly)\n")
    lines.append("- [ ] REDIS_PASSWORD configured (and REDIS_TLS=true)\n")
    lines.append("- [ ] QDRANT_API_KEY configured for cloud/secured deployments\n")
    lines.append("- [ ] All AI provider API keys configured (OPENROUTER_API_KEY, etc.)\n")
    lines.append("- [ ] N8N_API_KEY or credentials configured (if using n8n)\n")
    lines.append("- [ ] Firewall rules: only necessary ports open\n")
    lines.append("- [ ] SSH access restricted to VPN/bastion host\n")
    lines.append("- [ ] POSTGRES_SSLMODE=require (enforce SSL on database connections)\n")
    lines.append("- [ ] Production .env reviewed for accidental test values\n\n")

    lines.append("## Configuration\n\n")
    lines.append("- [ ] All required environment variables set (see [configuration.md](configuration.md))\n")
    lines.append("- [ ] config/config.toml reviewed and validated\n")
    lines.append("- [ ] AIOS_LOG_LEVEL=INFO or WARNING (not DEBUG)\n")
    lines.append("- [ ] POSTGRES_CONNECT_TIMEOUT set appropriately\n")
    lines.append("- [ ] REDIS_TIMEOUT configured for network conditions\n")
    lines.append("- [ ] QDRANT_DEFAULT_DIMENSIONS matches embedding model (default: 1536)\n")
    lines.append("- [ ] OmniRoute provider priorities configured in config.toml\n")
    lines.append("- [ ] N8N_SERVER_URL configured (if using n8n)\n\n")

    lines.append("## Database\n\n")
    lines.append("- [ ] PostgreSQL migrations run successfully (`python -m aios.migrations`)\n")
    lines.append("- [ ] PostgreSQL backup configured and tested\n")
    lines.append("- [ ] PostgreSQL connection pool size tuned\n")
    lines.append("- [ ] PostgreSQL indexes created and optimized\n")
    lines.append("- [ ] Qdrant collections initialized (auto-created on first run)\n")
    lines.append("- [ ] Qdrant snapshots/backup configured\n")
    lines.append("- [ ] Redis maxmemory policy set (allkeys-lru recommended)\n\n")

    lines.append("## Application\n\n")
    lines.append("- [ ] Application code at correct release tag/commit\n")
    lines.append("- [ ] All tests passing (`pytest core/tests/`)\n")
    lines.append("- [ ] Python dependencies up to date and pinned\n")
    lines.append("- [ ] Static analysis / linting passes\n")
    lines.append("- [ ] Application starts without errors on staging environment\n")
    lines.append("- [ ] Health check endpoints responding\n")
    lines.append("- [ ] All service integrations verified (PostgreSQL, Redis, Qdrant, n8n)\n\n")

    lines.append("## Monitoring & Observability\n\n")
    lines.append("- [ ] Prometheus deployed and scraping AIOS, postgres-exporter, redis-exporter\n")
    lines.append("- [ ] Grafana dashboards imported and displaying data\n")
    lines.append("- [ ] Alertmanager configured with on-call notification channels\n")
    lines.append("- [ ] Alert rules configured for all thresholds in [monitoring.md](monitoring.md)\n")
    lines.append("- [ ] Loki log aggregation configured\n")
    lines.append("- [ ] Log retention policy configured (minimum 30 days)\n\n")

    lines.append("## Backup & Disaster Recovery\n\n")
    lines.append("- [ ] PostgreSQL daily backup cron configured\n")
    lines.append("- [ ] Qdrant daily snapshot automation configured\n")
    lines.append("- [ ] Backup restoration tested on a staging environment\n")
    lines.append("- [ ] Backup retention policy set (30 days for DB, 90 days for config)\n")
    lines.append("- [ ] Disaster recovery runbook documented\n")
    lines.append("- [ ] RTO (2–4 hours) and RPO (24 hours) defined and accepted\n\n")

    lines.append("## Performance\n\n")
    lines.append("- [ ] Load testing completed against production-equivalent environment\n")
    lines.append("- [ ] Response time p95 < 500ms under expected load\n")
    lines.append("- [ ] PostgreSQL query performance analyzed (no full-table scans)\n")
    lines.append("- [ ] Redis cache hit rate > 80%\n")
    lines.append("- [ ] Qdrant vector search latency p95 < 100ms\n\n")

    lines.append("## Documentation\n\n")
    lines.append("- [ ] [deployment.md](deployment.md) reviewed by operations team\n")
    lines.append("- [ ] [startup.md](startup.md) used to verify startup sequence\n")
    lines.append("- [ ] [troubleshooting.md](troubleshooting.md) available on-call runbook\n")
    lines.append("- [ ] [backup_restore.md](backup_restore.md) referenced in DR plan\n")
    lines.append("- [ ] Architecture diagrams up to date: [docs/diagrams/](../diagrams/README.md)\n")
    lines.append("- [ ] On-call procedures documented and team notified\n\n")

    lines.append("## Post-Deployment Verification\n\n")
    lines.append("- [ ] Smoke tests passing (`./scripts/smoke-tests.sh`)\n")
    lines.append("- [ ] Monitor error rate for first 30 minutes post-deployment\n")
    lines.append("- [ ] Verify all service integrations working (PostgreSQL, Redis, Qdrant)\n")
    lines.append("- [ ] Verify n8n workflows triggering correctly (if configured)\n")
    lines.append("- [ ] OmniRoute model requests succeeding in logs\n")
    lines.append("- [ ] Rollback plan validated and ready if needed\n\n")

    lines.append("## Sign-Off\n\n")
    lines.append("- [ ] Technical lead approval obtained\n")
    lines.append("- [ ] Security review completed\n")
    lines.append("- [ ] Operations team notified of deployment window\n")
    lines.append("- [ ] Deployment scheduled and communicated to stakeholders\n")
    lines.append("- [ ] Rollback procedure tested and ready\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [configuration.md](configuration.md) — All environment variables\n")
    lines.append("- [deployment.md](deployment.md) — Deployment procedure\n")
    lines.append("- [startup.md](startup.md) — Service startup sequence\n")
    lines.append("- [monitoring.md](monitoring.md) — Alert thresholds\n")
    lines.append("- [backup_restore.md](backup_restore.md) — Backup verification\n")
    lines.append("- [troubleshooting.md](troubleshooting.md) — Issue resolution\n")

    return "".join(lines)
