"""
refgen_renderers.py — Renderers for API & Service Reference documentation.

Produces detailed API reference documentation in Markdown format.
"""

from __future__ import annotations

import datetime
from typing import List

from aios.docgen.refgen_models import (
    MethodSignature,
    ParameterInfo,
    ServiceInterface,
)

_TIMESTAMP_FMT = "%Y-%m-%dT%H:%M:%SZ"


def _banner() -> str:
    """Generate the auto-generated warning banner."""
    now = datetime.datetime.now(datetime.UTC).strftime(_TIMESTAMP_FMT)
    return f"""<!--
  ⚠  AUTO-GENERATED — DO NOT EDIT MANUALLY
  Generated by: aios.docgen reference generator
  Generated on: {now}
  This file is recreated on every generation run.
  Edit the source code and re-run the generator to update this file.
-->

"""


def _format_parameter(param: ParameterInfo) -> str:
    """Format a parameter as a string."""
    parts = [param.name]
    if param.type_annotation:
        parts.append(f": {param.type_annotation}")
    if param.default_value:
        parts.append(f" = {param.default_value}")
    return "".join(parts)


def _format_signature(sig: MethodSignature) -> str:
    """Format a method signature as a string."""
    prefix = ""
    if sig.is_async:
        prefix = "async "
    if sig.is_classmethod:
        prefix += "@classmethod "
    elif sig.is_staticmethod:
        prefix += "@staticmethod "
    elif sig.is_property:
        prefix += "@property "

    params_str = ", ".join(_format_parameter(p) for p in sig.parameters)
    return_str = f" -> {sig.return_type}" if sig.return_type else ""

    return f"{prefix}def {sig.name}({params_str}){return_str}"


def render_services_reference(services: List[ServiceInterface]) -> str:
    """Render the services.md reference with full API documentation."""
    lines = [_banner()]
    lines.append("# Service API Reference\n\n")
    lines.append(f"> Auto-generated API reference for {len(services)} services.\n\n")

    lines.append("## Summary\n\n")
    lines.append(f"- **Total Services**: {len(services)}\n")
    total_methods = sum(len(s.methods) for s in services)
    lines.append(f"- **Total Public Methods**: {total_methods}\n")
    total_lifecycle = sum(len(s.lifecycle_methods) for s in services)
    lines.append(f"- **Lifecycle Methods**: {total_lifecycle}\n\n")

    lines.append("## Services\n\n")
    for service in services:
        lines.append(f"### {service.name}\n\n")
        lines.append(f"**Module**: `{service.module}`\n\n")

        if service.docstring:
            lines.append(f"{service.docstring}\n\n")

        if service.base_classes:
            lines.append(
                f"**Base Classes**: {', '.join(f'`{b}`' for b in service.base_classes)}\n\n"
            )

        if service.implementation:
            lines.append(
                f"**Implementation**: `{service.implementation}` (`{service.impl_module}`)\n\n"
            )

        # Constructor
        if service.constructor_params:
            lines.append("#### Constructor\n\n")
            lines.append("```python\n")
            params_str = ", ".join(_format_parameter(p) for p in service.constructor_params)
            lines.append(f"def __init__({params_str})\n")
            lines.append("```\n\n")

            lines.append("**Dependencies**:\n\n")
            for param in service.constructor_params:
                req = "required" if param.is_required else "optional"
                type_str = f": {param.type_annotation}" if param.type_annotation else ""
                lines.append(f"- `{param.name}`{type_str} ({req})\n")
            lines.append("\n")

        # Public Methods
        if service.methods:
            lines.append("#### Public Methods\n\n")
            for method in service.methods:
                lines.append(f"##### `{method.name}`\n\n")
                lines.append("```python\n")
                lines.append(_format_signature(method) + "\n")
                lines.append("```\n\n")

                if method.docstring:
                    lines.append(f"{method.docstring}\n\n")

                if method.parameters:
                    lines.append("**Parameters**:\n\n")
                    for param in method.parameters:
                        type_str = f": {param.type_annotation}" if param.type_annotation else ""
                        default_str = (
                            f" (default: {param.default_value})" if param.default_value else ""
                        )
                        lines.append(f"- `{param.name}`{type_str}{default_str}\n")
                    lines.append("\n")

                if method.return_type:
                    lines.append(f"**Returns**: `{method.return_type}`\n\n")

                if method.exceptions:
                    lines.append(
                        f"**Raises**: {', '.join(f'`{e}`' for e in method.exceptions)}\n\n"
                    )

        # Lifecycle Methods
        if service.lifecycle_methods:
            lines.append("#### Lifecycle Methods\n\n")
            for lm in service.lifecycle_methods:
                lines.append(f"##### `{lm.name}` ({lm.phase})\n\n")
                lines.append("```python\n")
                lines.append(_format_signature(lm.signature) + "\n")
                lines.append("```\n\n")

                if lm.signature.docstring:
                    lines.append(f"{lm.signature.docstring}\n\n")

        lines.append("---\n\n")

    return "".join(lines)


def render_interfaces_reference(
    services: List[ServiceInterface],
) -> str:
    """Render the interfaces.md reference showing interface-to-implementation mappings."""
    lines = [_banner()]
    lines.append("# Interface to Implementation Reference\n\n")

    # Separate interfaces from standalone implementations
    interfaces = [s for s in services if not s.name.endswith("Impl")]
    implementations = [s for s in services if s.name.endswith("Impl")]

    lines.append(f"> Maps {len(interfaces)} interfaces to their concrete implementations.\n\n")

    lines.append("## Interface Registry\n\n")
    lines.append("| Interface | Implementation | Module |\n")
    lines.append("|-----------|----------------|--------|\n")

    for service in interfaces:
        impl = service.implementation or "N/A"
        impl_mod = service.impl_module or "N/A"
        lines.append(f"| `{service.name}` | `{impl}` | `{impl_mod}` |\n")

    lines.append("\n")

    lines.append("## Standalone Implementations\n\n")
    lines.append("> Services with no separate interface definition.\n\n")

    for service in implementations:
        if not any(s.implementation == service.name for s in interfaces):
            lines.append(f"- `{service.name}` (`{service.module}`)\n")

    lines.append("\n")

    lines.append("## Interface Details\n\n")
    for service in interfaces:
        lines.append(f"### {service.name}\n\n")
        lines.append(f"**Module**: `{service.module}`\n\n")

        if service.docstring:
            lines.append(f"{service.docstring}\n\n")

        lines.append(f"**Implementation**: `{service.implementation or 'None'}`\n\n")

        if service.methods:
            lines.append("**Interface Methods**:\n\n")
            for method in service.methods:
                sig = _format_signature(method)
                lines.append(f"- `{sig}`\n")
            lines.append("\n")

        lines.append("---\n\n")

    return "".join(lines)


def render_lifecycle_reference(services: List[ServiceInterface]) -> str:
    """Render the lifecycle.md reference documenting lifecycle methods."""
    lines = [_banner()]
    lines.append("# Service Lifecycle Reference\n\n")

    # Collect all lifecycle methods by phase
    initialization_methods = []
    runtime_methods = []
    cleanup_methods = []

    for service in services:
        for lm in service.lifecycle_methods:
            entry = (service.name, lm)
            if lm.phase == "initialization":
                initialization_methods.append(entry)
            elif lm.phase == "runtime":
                runtime_methods.append(entry)
            elif lm.phase == "cleanup":
                cleanup_methods.append(entry)

    total = len(initialization_methods) + len(runtime_methods) + len(cleanup_methods)
    lines.append(f"> Documents {total} lifecycle methods across {len(services)} services.\n\n")

    lines.append("## Lifecycle Phases\n\n")
    lines.append(
        "1. **Initialization**: Service setup, dependency injection, resource allocation\n"
    )
    lines.append("2. **Runtime**: Active service execution, request handling\n")
    lines.append("3. **Cleanup**: Resource release, connection closing, graceful shutdown\n\n")

    # Initialization Phase
    lines.append("## Initialization Phase\n\n")
    lines.append(f"> {len(initialization_methods)} initialization methods\n\n")

    for service_name, lm in initialization_methods:
        lines.append(f"### {service_name}.{lm.name}\n\n")
        lines.append("```python\n")
        lines.append(_format_signature(lm.signature) + "\n")
        lines.append("```\n\n")

        if lm.signature.docstring:
            lines.append(f"{lm.signature.docstring}\n\n")

        if lm.signature.parameters:
            lines.append("**Dependencies**:\n\n")
            for param in lm.signature.parameters:
                type_str = f": {param.type_annotation}" if param.type_annotation else ""
                lines.append(f"- `{param.name}`{type_str}\n")
            lines.append("\n")

    # Runtime Phase
    if runtime_methods:
        lines.append("## Runtime Phase\n\n")
        lines.append(f"> {len(runtime_methods)} runtime methods\n\n")

        for service_name, lm in runtime_methods:
            lines.append(f"### {service_name}.{lm.name}\n\n")
            lines.append("```python\n")
            lines.append(_format_signature(lm.signature) + "\n")
            lines.append("```\n\n")

            if lm.signature.docstring:
                lines.append(f"{lm.signature.docstring}\n\n")

    # Cleanup Phase
    lines.append("## Cleanup Phase\n\n")
    lines.append(f"> {len(cleanup_methods)} cleanup methods\n\n")

    for service_name, lm in cleanup_methods:
        lines.append(f"### {service_name}.{lm.name}\n\n")
        lines.append("```python\n")
        lines.append(_format_signature(lm.signature) + "\n")
        lines.append("```\n\n")

        if lm.signature.docstring:
            lines.append(f"{lm.signature.docstring}\n\n")

    return "".join(lines)


def render_dependency_injection_reference(services: List[ServiceInterface]) -> str:
    """Render the dependency_injection.md reference documenting DI bindings."""
    lines = [_banner()]
    lines.append("# Dependency Injection Reference\n\n")

    # Extract all constructor dependencies
    all_dependencies = []
    for service in services:
        if service.constructor_params:
            for param in service.constructor_params:
                all_dependencies.append((service.name, param))

    lines.append(f"> Documents constructor dependencies for {len(services)} services.\n\n")

    lines.append("## Dependency Graph Summary\n\n")
    lines.append(
        f"- **Services with dependencies**: {sum(1 for s in services if s.constructor_params)}\n"
    )
    lines.append(f"- **Total injected dependencies**: {len(all_dependencies)}\n\n")

    lines.append("## Service Dependencies\n\n")
    for service in services:
        if not service.constructor_params:
            continue

        lines.append(f"### {service.name}\n\n")
        lines.append(f"**Module**: `{service.module}`\n\n")

        lines.append("**Constructor**:\n\n")
        lines.append("```python\n")
        params_str = ", ".join(_format_parameter(p) for p in service.constructor_params)
        lines.append(f"def __init__({params_str})\n")
        lines.append("```\n\n")

        lines.append("**Injected Dependencies**:\n\n")
        lines.append("| Parameter | Type | Required |\n")
        lines.append("|-----------|------|----------|\n")
        for param in service.constructor_params:
            type_str = param.type_annotation or "Any"
            req = "Yes" if param.is_required else "No"
            lines.append(f"| `{param.name}` | `{type_str}` | {req} |\n")
        lines.append("\n")

    return "".join(lines)


def render_api_reference(services: List[ServiceInterface]) -> str:
    """Render the api_reference.md complete API reference."""
    lines = [_banner()]
    lines.append("# Complete API Reference\n\n")
    lines.append("> Comprehensive API documentation for all services.\n\n")

    lines.append("## Table of Contents\n\n")
    for service in services:
        anchor = service.name.lower().replace(" ", "-")
        lines.append(f"- [{service.name}](#{anchor})\n")
    lines.append("\n")

    lines.append("---\n\n")

    for service in services:
        lines.append(f"## {service.name}\n\n")
        lines.append(f"**Module**: `{service.module}`\n\n")
        lines.append(f"**File**: `{service.file_path}`\n\n")

        if service.docstring:
            lines.append(f"**Description**: {service.docstring}\n\n")

        if service.base_classes:
            lines.append(f"**Extends**: {', '.join(f'`{b}`' for b in service.base_classes)}\n\n")

        if service.implementation:
            lines.append(
                f"**Implementation**: [`{service.implementation}`](#{service.implementation.lower()})\n\n"
            )

        # Constructor
        if service.constructor_params:
            lines.append("### Constructor\n\n")
            lines.append("```python\n")
            params_str = ", ".join(_format_parameter(p) for p in service.constructor_params)
            lines.append(f"def __init__({params_str})\n")
            lines.append("```\n\n")

        # Methods
        if service.methods:
            lines.append("### Methods\n\n")
            for method in service.methods:
                lines.append(f"#### `{method.name}`\n\n")
                lines.append("```python\n")
                lines.append(_format_signature(method) + "\n")
                lines.append("```\n\n")

                if method.docstring:
                    lines.append(f"{method.docstring}\n\n")

                if method.parameters:
                    lines.append("**Parameters**:\n\n")
                    for param in method.parameters:
                        type_str = f": `{param.type_annotation}`" if param.type_annotation else ""
                        default_str = f" = `{param.default_value}`" if param.default_value else ""
                        lines.append(f"- `{param.name}`{type_str}{default_str}\n")
                    lines.append("\n")

                if method.return_type:
                    lines.append(f"**Returns**: `{method.return_type}`\n\n")

                if method.exceptions:
                    lines.append(
                        f"**Raises**: {', '.join(f'`{e}`' for e in method.exceptions)}\n\n"
                    )

        # Lifecycle
        if service.lifecycle_methods:
            lines.append("### Lifecycle\n\n")
            for lm in service.lifecycle_methods:
                lines.append(f"#### `{lm.name}` ({lm.phase})\n\n")
                lines.append("```python\n")
                lines.append(_format_signature(lm.signature) + "\n")
                lines.append("```\n\n")

        lines.append("---\n\n")

    return "".join(lines)


def render_reference_index(services: List[ServiceInterface]) -> str:
    """Render the README.md index for the reference documentation."""
    lines = [_banner()]
    lines.append("# API & Service Reference\n\n")
    lines.append("> Auto-generated API reference documentation.\n\n")

    now = datetime.datetime.now(datetime.UTC).strftime(_TIMESTAMP_FMT)
    lines.append(f"**Generated**: {now}\n\n")

    lines.append("## Overview\n\n")
    lines.append(
        f"This directory contains detailed API reference documentation for {len(services)} services "
    )
    lines.append("extracted from source code.\n\n")

    lines.append("## Documentation Files\n\n")
    lines.append("| File | Description |\n")
    lines.append("|------|-------------|\n")
    lines.append(
        "| [services.md](services.md) | Complete service API documentation with method signatures |\n"
    )
    lines.append("| [interfaces.md](interfaces.md) | Interface to implementation mappings |\n")
    lines.append("| [lifecycle.md](lifecycle.md) | Service lifecycle methods (init, cleanup) |\n")
    lines.append(
        "| [dependency_injection.md](dependency_injection.md) | Constructor dependencies and DI bindings |\n"
    )
    lines.append(
        "| [api_reference.md](api_reference.md) | Comprehensive API reference (all services) |\n\n"
    )

    lines.append("## Statistics\n\n")
    total_methods = sum(len(s.methods) for s in services)
    total_lifecycle = sum(len(s.lifecycle_methods) for s in services)
    services_with_deps = sum(1 for s in services if s.constructor_params)

    lines.append(f"- **Services**: {len(services)}\n")
    lines.append(f"- **Public Methods**: {total_methods}\n")
    lines.append(f"- **Lifecycle Methods**: {total_lifecycle}\n")
    lines.append(f"- **Services with DI Dependencies**: {services_with_deps}\n\n")

    lines.append("## Regeneration\n\n")
    lines.append("To regenerate this reference documentation:\n\n")
    lines.append("```bash\n")
    lines.append("python -m aios.docgen.refgen\n")
    lines.append("```\n\n")

    lines.append("## Cross-References\n\n")
    lines.append("- [Generated Documentation](../generated/README.md) - Component catalogs\n")
    lines.append("- [Architecture Documentation](../architecture/README.md) - System design\n")
    lines.append("- [Service Documentation](../services/README.md) - Service guides\n")

    return "".join(lines)
