"""
docgen/renderers.py — Markdown renderers for each catalog type.

Each renderer receives discovered data and returns a complete Markdown string.
Renderers are pure functions — they have no side effects and can be tested
independently.
"""

from __future__ import annotations

import datetime
from typing import List

from aios.docgen.models import (
    DbModelEntry,
    DIBinding,
    ProviderEntry,
    RepositoryEntry,
    RuntimeComponentEntry,
    ServiceEntry,
    SkillEntry,
)

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

_GENERATED_BANNER = """\
<!--
  ⚠  AUTO-GENERATED — DO NOT EDIT MANUALLY
  Generated by: aios.docgen.engine.DocGeneratorEngine
  This file is recreated on every `python -m aios.docgen` invocation.
  Edit the source code and re-run the generator to update this file.
-->
"""

_TIMESTAMP_FMT = "%Y-%m-%dT%H:%M:%SZ"


def _header(title: str, description: str) -> str:
    now = datetime.datetime.utcnow().strftime(_TIMESTAMP_FMT)
    return f"{_GENERATED_BANNER}\n# {title}\n\n> {description}\n\n*Generated: {now}*\n\n---\n\n"


def _toc(items: List[str]) -> str:
    """Render a simple Table of Contents from section headings."""
    lines = ["## Table of Contents\n"]
    for item in items:
        anchor = item.lower().replace(" ", "-").replace("/", "")
        lines.append(f"- [{item}](#{anchor})")
    return "\n".join(lines) + "\n\n---\n\n"


def _badge(label: str, value: str, color: str = "blue") -> str:
    label_enc = label.replace(" ", "_")
    value_enc = value.replace(" ", "_")
    return f"![{label}](https://img.shields.io/badge/{label_enc}-{value_enc}-{color})"


# ---------------------------------------------------------------------------
# Service Catalog Renderer
# ---------------------------------------------------------------------------


def render_service_catalog(services: List[ServiceEntry]) -> str:
    """Produce a Markdown Service Catalog document."""
    lines: List[str] = []
    lines.append(
        _header(
            "Service Catalog",
            "All service interfaces registered in the Personal AI OS service registry, "
            "their implementations, and exposed API contracts.",
        )
    )
    lines.append(_toc(["Overview", "Services", "Summary Statistics"]))

    # Overview
    lines.append("## Overview\n")
    lines.append(
        f"The AIOS service layer exposes **{len(services)} service interfaces**, each "
        "paired with a concrete local or remote implementation. All services implement "
        "`ServiceLifecycle` and are wired via the Composition Root in `bootstrap.py`.\n\n"
    )

    # Services
    lines.append("## Services\n")
    for svc in services:
        lines.append(f"### {svc.name}\n")

        # Badges
        has_impl = "✅ Yes" if svc.implementation else "⚠️ No"
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **Module** | `{svc.module}` |")
        lines.append(f"| **File** | `{svc.file_path}` |")
        lines.append(f"| **Bases** | {', '.join(f'`{b}`' for b in svc.base_classes) or '—'} |")
        lines.append(f"| **Implementation** | `{svc.implementation or '—'}` |")
        lines.append(f"| **Impl Module** | `{svc.impl_module or '—'}` |")
        lines.append(f"| **Has Implementation** | {has_impl} |")
        lines.append("")

        if svc.docstring:
            lines.append(f"**Description:** {svc.docstring}\n")

        if svc.methods:
            lines.append("**Public Methods:**\n")
            for m in sorted(svc.methods):
                lines.append(f"- `{m}()`")
            lines.append("")

        lines.append("---\n")

    # Stats
    lines.append("## Summary Statistics\n")
    with_impl = sum(1 for s in services if s.implementation)
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Services | {len(services)} |")
    lines.append(f"| With Implementations | {with_impl} |")
    lines.append(f"| Without Implementations | {len(services) - with_impl} |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Repository Catalog Renderer
# ---------------------------------------------------------------------------


def render_repository_catalog(repositories: List[RepositoryEntry]) -> str:
    """Produce a Markdown Repository Catalog document."""
    lines: List[str] = []
    lines.append(
        _header(
            "Repository Catalog",
            "All repository abstractions and their PostgreSQL implementations in the "
            "AIOS Persistence Platform.",
        )
    )
    lines.append(_toc(["Overview", "Repositories", "Summary Statistics"]))

    lines.append("## Overview\n")
    lines.append(
        f"The Persistence Platform provides **{len(repositories)} repository interfaces**. "
        "Each repository encapsulates database access for a specific domain entity and "
        "implements `ServiceLifecycle`.\n\n"
    )

    lines.append("## Repositories\n")
    for repo in repositories:
        lines.append(f"### {repo.name}\n")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **Entity** | `{repo.entity or '—'}` |")
        lines.append(f"| **Module** | `{repo.module}` |")
        lines.append(f"| **File** | `{repo.file_path}` |")
        lines.append(f"| **Bases** | {', '.join(f'`{b}`' for b in repo.base_classes) or '—'} |")
        lines.append(f"| **Implementation** | `{repo.implementation or '—'}` |")
        lines.append("")

        if repo.docstring:
            lines.append(f"**Description:** {repo.docstring}\n")

        if repo.methods:
            lines.append("**Operations:**\n")
            for m in sorted(repo.methods):
                lines.append(f"- `{m}()`")
            lines.append("")

        lines.append("---\n")

    lines.append("## Summary Statistics\n")
    with_impl = sum(1 for r in repositories if r.implementation)
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Repositories | {len(repositories)} |")
    lines.append(f"| With Implementations | {with_impl} |")
    lines.append(f"| Abstract Only | {len(repositories) - with_impl} |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Skill Catalog Renderer
# ---------------------------------------------------------------------------


def render_skill_catalog(skills: List[SkillEntry]) -> str:
    """Produce a Markdown Skill Catalog document."""
    lines: List[str] = []
    lines.append(
        _header(
            "Skill Catalog",
            "All installable skills in the Personal AI OS skills library, "
            "their commands, capabilities, and requirements.",
        )
    )
    lines.append(_toc(["Overview", "Skills", "Skill Matrix"]))

    lines.append("## Overview\n")
    lines.append(
        f"The AIOS skills system contains **{len(skills)} skills** that extend the OS "
        "capabilities with domain-specific commands and capabilities. Skills are loaded "
        "from `skill.toml` manifests.\n\n"
    )

    lines.append("## Skills\n")
    for skill in skills:
        lines.append(f"### {skill.name}\n")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **ID** | `{skill.skill_id}` |")
        lines.append(f"| **Version** | `{skill.version}` |")
        lines.append(f"| **Author** | {skill.author} |")
        lines.append(f"| **Category** | {skill.category} |")
        lines.append(f"| **Has Commands** | {'✅ Yes' if skill.has_commands_py else '⚠️ No'} |")
        lines.append(f"| **TOML Path** | `{skill.toml_path}` |")
        lines.append("")

        lines.append(f"**Description:** {skill.description}\n")

        if skill.commands:
            lines.append("**Commands:**\n")
            for cmd in skill.commands:
                lines.append(f"- `{cmd}`")
            lines.append("")

        if skill.capabilities:
            lines.append(f"**Capabilities:** {', '.join(f'`{c}`' for c in skill.capabilities)}\n")

        if skill.required_models:
            lines.append(
                f"**Required Models:** {', '.join(f'`{m}`' for m in skill.required_models)}\n"
            )

        if skill.required_tools:
            lines.append(
                f"**Required Tools:** {', '.join(f'`{t}`' for t in skill.required_tools)}\n"
            )

        lines.append("---\n")

    # Skill Matrix
    lines.append("## Skill Matrix\n")
    lines.append("| Skill | Version | Category | Commands | Capabilities |")
    lines.append("|-------|---------|----------|----------|--------------|")
    for skill in skills:
        cmds = len(skill.commands)
        caps = len(skill.capabilities)
        lines.append(f"| **{skill.name}** | {skill.version} | {skill.category} | {cmds} | {caps} |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Provider Catalog Renderer
# ---------------------------------------------------------------------------


def render_provider_catalog(providers: List[ProviderEntry]) -> str:
    """Produce a Markdown Provider Catalog document."""
    lines: List[str] = []
    lines.append(
        _header(
            "Provider Catalog",
            "All registered AI model providers in the AIOS OmniRoute engine, "
            "their capabilities, costs, and routing priorities.",
        )
    )
    lines.append(_toc(["Overview", "Providers", "Cost Comparison", "Capability Matrix"]))

    lines.append("## Overview\n")
    lines.append(
        f"The OmniRoute provider layer supports **{len(providers)} AI providers**. "
        "Routing decisions are made automatically based on capability, cost, latency, "
        "and health signals.\n\n"
    )

    lines.append("## Providers\n")
    for p in sorted(providers, key=lambda x: x.priority):
        lines.append(f"### {p.name}\n")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **Version** | `{p.version}` |")
        lines.append(f"| **Status** | `{p.status}` |")
        lines.append(f"| **Priority** | {p.priority} |")
        lines.append(f"| **Context Window** | {p.context_window:,} tokens |")
        lines.append(f"| **Input Cost** | ${p.cost_per_million_input:.2f} / M tokens |")
        lines.append(f"| **Output Cost** | ${p.cost_per_million_output:.2f} / M tokens |")
        lines.append(f"| **Auth Type** | `{p.auth_type}` |")
        lines.append(f"| **Is Local** | {'Yes' if p.is_local else 'No'} |")
        lines.append("")

        if p.supported_models:
            lines.append(
                f"**Supported Models:** {', '.join(f'`{m}`' for m in p.supported_models)}\n"
            )

        if p.capabilities:
            cap_bullets = [f"`{k}`: {'✅' if v else '❌'}" for k, v in p.capabilities.items()]
            lines.append("**Capabilities:**\n")
            for cap in cap_bullets:
                lines.append(f"- {cap}")
            lines.append("")

        lines.append("---\n")

    # Cost comparison table
    lines.append("## Cost Comparison\n")
    lines.append("| Provider | Context Window | Input $/M | Output $/M | Priority |")
    lines.append("|----------|---------------|-----------|------------|----------|")
    for p in sorted(providers, key=lambda x: x.cost_per_million_input):
        lines.append(
            f"| **{p.name}** | {p.context_window:,} | "
            f"${p.cost_per_million_input:.2f} | ${p.cost_per_million_output:.2f} | {p.priority} |"
        )
    lines.append("")

    # Capability matrix
    lines.append("## Capability Matrix\n")
    all_caps = sorted({cap for p in providers for cap in p.capabilities.keys()})
    header = "| Provider | " + " | ".join(all_caps) + " |"
    sep = "|---------|" + "|".join(["---"] * len(all_caps)) + "|"
    lines.append(header)
    lines.append(sep)
    for p in sorted(providers, key=lambda x: x.priority):
        row_caps = " | ".join(("✅" if p.capabilities.get(cap) else "❌") for cap in all_caps)
        lines.append(f"| **{p.name}** | {row_caps} |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Runtime Component Catalog Renderer
# ---------------------------------------------------------------------------


def render_runtime_catalog(components: List[RuntimeComponentEntry]) -> str:
    """Produce a Markdown Runtime Component Catalog."""
    lines: List[str] = []
    lines.append(
        _header(
            "Runtime Component Catalog",
            "All concrete runtime components registered via the Composition Root "
            "(bootstrap.py / bootstrap_modules/). These are the actual implementations "
            "wired into the kernel.",
        )
    )
    lines.append(_toc(["Overview", "Components", "Summary Statistics"]))

    lines.append("## Overview\n")
    lines.append(
        f"The AIOS runtime registers **{len(components)} concrete components** during "
        "bootstrap. Each component implements one or more service interfaces via "
        "dependency injection.\n\n"
    )

    lines.append("## Components\n")
    for comp in components:
        lines.append(f"### {comp.name}\n")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **Module** | `{comp.module}` |")
        lines.append(f"| **File** | `{comp.file_path}` |")
        lines.append(f"| **Interface** | `{comp.interface or '—'}` |")
        lines.append(f"| **Bases** | {', '.join(f'`{b}`' for b in comp.base_classes) or '—'} |")
        lines.append("")

        if comp.docstring:
            lines.append(f"**Description:** {comp.docstring}\n")

        lines.append("---\n")

    lines.append("## Summary Statistics\n")
    with_iface = sum(1 for c in components if c.interface)
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Components | {len(components)} |")
    lines.append(f"| With Identified Interface | {with_iface} |")
    lines.append(f"| Anonymous | {len(components) - with_iface} |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Dependency Graph Renderer (Mermaid)
# ---------------------------------------------------------------------------


def render_dependency_graph(bindings: List[DIBinding]) -> str:
    """Produce a Mermaid dependency graph document."""
    lines: List[str] = []
    lines.append(
        _header(
            "Dependency Graph",
            "DI binding graph showing which concrete class is registered under each "
            "interface in the AIOS Service Registry (extracted from bootstrap.py).",
        )
    )

    lines.append("## Overview\n")
    lines.append(
        f"The Composition Root registers **{len(bindings)} DI bindings**. "
        "The graph below visualises the interface → concrete mappings.\n\n"
    )

    lines.append("## DI Bindings Table\n")
    lines.append("| # | Interface | Concrete | Line |")
    lines.append("|---|-----------|----------|------|")
    for i, b in enumerate(bindings, 1):
        lines.append(f"| {i} | `{b.interface}` | `{b.concrete}` | L{b.line_number} |")
    lines.append("")

    # Mermaid graph (top-level grouping)
    lines.append("## Dependency Graph (Mermaid)\n")
    lines.append("```mermaid")
    lines.append("graph LR")
    lines.append('  subgraph "AIOS DI Bindings"')

    for b in bindings:
        iface_node = b.interface.replace(" ", "_")
        conc_node = b.concrete.replace(" ", "_")
        lines.append(f'    {iface_node}["{b.interface}"] --> {conc_node}["{b.concrete}"]')

    lines.append("  end")
    lines.append("```\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# DB Model Catalog Renderer
# ---------------------------------------------------------------------------


def render_db_model_catalog(models: List[DbModelEntry]) -> str:
    """Produce a Markdown Database Model Catalog."""
    lines: List[str] = []
    lines.append(
        _header(
            "Database Model Catalog",
            "All dataclasses, enumerations, and data models discovered in the AIOS "
            "service layer. These models represent the core domain entities.",
        )
    )

    enums = [m for m in models if m.kind == "enum"]
    dataclasses_ = [m for m in models if m.kind == "dataclass"]
    classes_ = [m for m in models if m.kind == "class"]

    lines.append(
        _toc(["Overview", "Enumerations", "Dataclasses", "Other Models", "Summary Statistics"])
    )

    lines.append("## Overview\n")
    lines.append(
        f"The domain model layer contains **{len(models)} model types**: "
        f"{len(enums)} enumerations, {len(dataclasses_)} dataclasses, and "
        f"{len(classes_)} class-based models.\n\n"
    )

    def _render_section(section_models: List[DbModelEntry], section_name: str) -> None:
        lines.append(f"## {section_name}\n")
        if not section_models:
            lines.append("_None discovered._\n")
            return
        for m in section_models:
            lines.append(f"### {m.name}\n")
            lines.append("| Field | Value |")
            lines.append("|-------|-------|")
            lines.append(f"| **Kind** | `{m.kind}` |")
            lines.append(f"| **Module** | `{m.module}` |")
            lines.append(f"| **Line** | L{m.line_number} |")
            lines.append("")

            if m.docstring:
                lines.append(f"**Description:** {m.docstring}\n")

            if m.fields:
                field_label = "Values" if m.kind == "enum" else "Fields"
                lines.append(f"**{field_label}:**\n")
                for fld in m.fields:
                    lines.append(f"- `{fld}`")
                lines.append("")

            lines.append("---\n")

    _render_section(enums, "Enumerations")
    _render_section(dataclasses_, "Dataclasses")
    _render_section(classes_, "Other Models")

    lines.append("## Summary Statistics\n")
    lines.append("| Model Type | Count |")
    lines.append("|------------|-------|")
    lines.append(f"| Enumerations | {len(enums)} |")
    lines.append(f"| Dataclasses | {len(dataclasses_)} |")
    lines.append(f"| Other Models | {len(classes_)} |")
    lines.append(f"| **Total** | **{len(models)}** |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Index Renderer
# ---------------------------------------------------------------------------


def render_index(
    *,
    services_count: int,
    repositories_count: int,
    skills_count: int,
    providers_count: int,
    runtime_count: int,
    db_models_count: int,
    di_bindings_count: int,
    generated_files: List[str],
) -> str:
    """Produce a top-level index / README for docs/generated/."""
    now = datetime.datetime.utcnow().strftime(_TIMESTAMP_FMT)
    lines: List[str] = [
        _GENERATED_BANNER,
        "# AIOS Generated Documentation\n",
        f"> Auto-generated on **{now}** by `aios.docgen.engine.DocGeneratorEngine`.\n",
        "> Do not edit this directory manually — re-run the generator to update.\n\n",
        "---\n",
        "## Discovery Summary\n",
        "| Category | Discovered |",
        "|----------|------------|",
        f"| Services | {services_count} |",
        f"| Repositories | {repositories_count} |",
        f"| Skills | {skills_count} |",
        f"| Providers | {providers_count} |",
        f"| Runtime Components | {runtime_count} |",
        f"| DB Models | {db_models_count} |",
        f"| DI Bindings | {di_bindings_count} |",
        "",
        "## Generated Files\n",
    ]
    for f in sorted(generated_files):
        fname = f.split("/")[-1]
        lines.append(f"- [{fname}]({fname})")
    lines.append("")
    lines.append("## Regeneration\n")
    lines.append(
        "Run the generator from the repository root:\n\n```bash\npython -m aios.docgen\n```\n"
    )
    return "\n".join(lines)
