import abc
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from aios.services.base import ServiceLifecycle


@dataclass
class IntentContext:
    """Tracks variables, context information, and retrieved memories."""
    variables: Dict[str, Any] = field(default_factory=dict)
    memories: List[str] = field(default_factory=list)


@dataclass
class IntentPlan:
    """Represents a structured execution graph generated by the Intent Engine."""
    plan_id: str
    objective: str
    intents: List[str]
    participating_services: List[str]
    execution_order: List[str]
    dependencies: Dict[str, List[str]]
    expected_outputs: Dict[str, str]
    context_requirements: Dict[str, Any]


@dataclass
class IntentResult:
    """Represents the output of the Intent Engine analysis and planning step."""
    success: bool
    plan: Optional[IntentPlan] = None
    error_message: Optional[str] = None


class IntentClassifier(abc.ABC):
    """Classifies user queries into one or more system categories."""

    @abc.abstractmethod
    def classify(self, text: str) -> List[str]:
        """Classifies text into categories: Career, Project, Research, Learning, Automation, Planning, Coding, GitHub, Knowledge, Mission, Daily, Conversation, Hybrid."""
        pass


class IntentAnalyzer(abc.ABC):
    """Analyzes context dependencies and requirements for a set of categories."""

    @abc.abstractmethod
    def analyze(self, text: str, context: IntentContext) -> Dict[str, Any]:
        """Analyzes context requirements, dependencies, and expected outputs for categories."""
        pass


class IntentResolver(abc.ABC):
    """Resolves natural language objectives into structured IntentPlans."""

    @abc.abstractmethod
    def resolve_plan(self, text: str, context: IntentContext) -> IntentPlan:
        """Translates a user objective and context into a structured IntentPlan execution graph."""
        pass


class IntentEngine(ServiceLifecycle, abc.ABC):
    """The conductor service determining which capabilities participate to achieve the objective."""

    @abc.abstractmethod
    def process_objective(self, objective: str) -> IntentResult:
        """Processes the objective, retrieves memories, plans service orchestration, and evaluates safety."""
        pass
